USE [master]
GO
CREATE LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST] FROM WINDOWS WITH DEFAULT_DATABASE=[master]


USE [KonsDb_L1_Quality]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

