USE [xxd0vss]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [xxdvss_hf]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [xxd0vss_hf]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [xxd1vss_hf]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
