UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Obyt. dům s nebyt. prostory do 20 bytů' WHERE Id=7;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Dům do 20 bytových jednotek s nebyt. prostory' WHERE Id=8;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Obyt. dům s nebyt. prostory nad 20 bytů' WHERE Id=9;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Dům nad 20 bytových jednotek s nebyt. prostory' WHERE Id=10;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Obytný dům bez nebyt. prostor' WHERE Id=11;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Zemědělská půda 1 - 5 ha' WHERE Id=14;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Zemědělská půda 5 - 10 ha' WHERE Id=15;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Hotel do 20 lůžek' WHERE Id=17;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Objekt občanské vybavenosti (max. 2NP, do 500 m2)' WHERE Id=18;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Provozní objekt (max. 2NP, do 500 m2)' WHERE Id=20;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Polyfunkční objekt (max. 4NP, do 500 m2)' WHERE Id=23;
UPDATE [dbo].[RealEstateSubtypes] SET ShortName=N'Čerpací stanice pohonných hmot /phm' WHERE Id=29;
