update SqlQuery set SqlQueryText=REPLACE(SqlQueryText, 'SYSDATETIME()', 'CAST(GETDATE() as date)');

UPDATE SqlQuery SET SqlQueryText='WITH terms AS (SELECT * FROM (VALUES <terms>) T(term))
SELECT DEVELOPER_ID ''DeveloperId'', NAZEV ''DeveloperName'', ICO_RC ''DeveloperCIN'', null ''DeveloperProjectId'', null ''DeveloperProjectName''
FROM (
    SELECT A.DEVELOPER_ID, A.NAZEV, A.ICO_RC,
    (
        SELECT SUM(rate) FROM(
            SELECT CAST(CAST(CHARINDEX(term, ISNULL(A.NAZEV,'''')) AS BIT) AS INT)*1.01 + CAST(CAST(CHARINDEX(term, ISNULL(A.ICO_RC,'''')) AS BIT) AS INT) AS rate FROM terms
        )r
    ) AS RATE
    FROM [SBR].[HTEDM_CIS_DEVELOPER] A
    WHERE CAST(GETDATE() as date) BETWEEN A.[PLATNOST_OD] AND ISNULL(A.[PLATNOST_DO], ''9999-12-31'')
)s
WHERE RATE > 0
ORDER BY RATE DESC, NAZEV ASC' WHERE SqlQueryId='DeveloperSearch';

UPDATE SqlQuery SET SqlQueryText='WITH terms AS (SELECT * FROM (VALUES <terms>) T(term))
SELECT DEVELOPER_ID ''DeveloperId'', NAZEV ''DeveloperName'', ICO_RC ''DeveloperCIN'', DEVELOPER_PROJEKT_ID ''DeveloperProjectId'', PROJEKT ''DeveloperProjectName''
FROM (
	SELECT A.DEVELOPER_ID, A.NAZEV, A.ICO_RC, B.DEVELOPER_PROJEKT_ID, B.PROJEKT,
	(
		SELECT SUM(rate) FROM(
			SELECT CAST(CAST(CHARINDEX(term, ISNULL(A.NAZEV,'''')) AS BIT) AS INT)*1.01 + CAST(CAST(CHARINDEX(term, ISNULL(B.PROJEKT,'''')) AS BIT) AS INT) + CAST(CAST(CHARINDEX(term, ISNULL(A.ICO_RC,'''')) AS BIT) AS INT) AS rate FROM terms
		)r
	) AS RATE
	FROM [SBR].[HTEDM_CIS_DEVELOPER] A
	INNER JOIN [SBR].[HTEDM_CIS_DEV_PROJEKTY_SPV] B ON A.DEVELOPER_ID=B.DEVELOPER_ID
	WHERE CAST(GETDATE() as date) BETWEEN A.[PLATNOST_OD] AND ISNULL(A.[PLATNOST_DO], ''9999-12-31'') AND CAST(GETDATE() as date) BETWEEN B.[PLATNOST_OD] AND ISNULL(B.[PLATNOST_DO], ''9999-12-31'')
)s
WHERE RATE > 0 
ORDER BY RATE DESC, NAZEV ASC, PROJEKT ASC' WHERE SqlQueryId='DeveloperSearchWithProjects';

UPDATE SqlQuery SET SqlQueryText='SELECT KOD_PRODUKTU ''Id'', NAZOV_PRODUKTU ''Name'', PORADIE_ZOBRAZENIA ''Order'', MIN_VYSKA_UV ''LoanAmountMin'', MAX_VYSKA_UV ''LoanAmountMax'', MIN_SPLATNOST_V_ROKOCH ''LoanDurationMin'', MAX_SPLATNOST_V_ROKOCH ''LoanDurationMax'', MIN_VYSKA_LTV ''LtvMin'', MAX_VYSKA_LTV ''LtvMax'', DRUH_UV_POVOLENY ''MpHomeApiLoanType'', CAST(CASE WHEN CAST(GETDATE() as date) BETWEEN PLATNOST_OD_ES AND ISNULL(PLATNOST_DO_ES,''2099-01-01'') THEN 1 ELSE 0 END as bit) ''IsValid'', ID_PRODUKTU_PCP ''PcpProductId''
FROM SBR.HTEDM_CIS_HYPOTEKY_PRODUKTY
ORDER BY PORADIE_ZOBRAZENIA ASC' WHERE SqlQueryId='ProductTypes1';

UPDATE SqlQuery SET SqlQueryText='SELECT CAST(KOD as int) ''Id'', MAX(CODE) ''Code'', MAX(KOD_E_PODPISY) ''IdESign'', MAX(TEXT) ''Name'', CAST(CASE WHEN MAX(ISNULL(PLATNOST_DO, ''2099-01-01'')) > CAST(GETDATE() as date) THEN 1 ELSE 0 END as bit) ''IsValid'' FROM [SBR].HTEDM_CIS_PODPISOVE_METODY GROUP BY KOD' WHERE SqlQueryId='SigningMethods';
