# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: MPSS Common

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  projectFile: 'NOBY\NOBY.Api\NOBY.Api.csproj'
  dbMigrationsDirectory: 'NOBY\DatabaseMigrations'
  runSonarQube: $[or(contains(lower(variables['Build.SourceBranch']), 'release'), ne(lower(variables['USESONARQUBE']), 'false'))]

# custom BuildNumber
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)_$(Build.BuildId)

steps:

#- task: UseDotNet@2
#  inputs:
#    packageType: 'sdk'
#    version: '6.0.x'
#    includePreviewVersions: true

- task: InlinePowershell@1
  inputs:
    Script: |
      $file = '$(Build.SourcesDirectory)\$(projectFile)'
      $regex = '(?<=<Version>)[^<]*'
      
      $buildVersion='$(Build.BuildId)'
      
      $versionFromFile = Select-String -Path $file $regex
      $versionFromFile = $versionFromFile.Matches[0].Value
      $versionFromFile = $versionFromFile.Substring(0, $versionFromFile.lastIndexOf('.'))
      
      $finalVersion = $versionFromFile + "." + $buildVersion
     
      (Get-Content $file) -replace $regex, $finalversion | Set-Content $file
 
      Write-Host "Build.BuildNumber - " -NoNewline
      Write-Host $(Build.BuildNumber)
      Write-Host "Build.BuildId - " -NoNewline
      Write-Host $(Build.BuildId)
      Write-Host "Final version - " -NoNewline
      Write-Host $finalVersion


- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projectFile)'
    feedsToUse: 'config'
    nugetConfigPath: 'C:\Users\XX_TFSAGENT_MPSS\AppData\Roaming\NuGet\NuGet.Config'
    noCache: false

- task: SonarQubePrepare@5
  condition: and(succeeded(), eq(variables.runSonarQube, true))
  inputs:
    SonarQube: 'NOBY - SonarQube'
    scannerMode: 'MSBuild'
    projectKey: 'NOBY.FEAPI'
    projectName: 'NOBY.FEAPI'
    projectVersion: '1.0.0.$(Build.BuildId)'
    extraProperties: 'sonar.verbose=true'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectFile)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.BinariesDirectory)'
    noCache: false

- task: SonarQubeAnalyze@5
  condition: and(succeeded(), eq(variables.runSonarQube, true))

- task: SonarQubePublish@5
  condition: and(succeeded(), eq(variables.runSonarQube, true))
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: '\\sapckb079\NETDEV\BuildsMPSS\NOBY\$(Build.DefinitionName)\$(Build.BuildNumber)'

- task: ArchiveFiles@2
  displayName: 'Archive DB Migrations'
  condition: and(succeeded(), ne(variables.dbMigrationsDirectory, ''))
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/$(dbMigrationsDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)_DB.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish DB Migrations to Artifacts'
  condition: and(succeeded(), ne(variables.dbMigrationsDirectory, ''))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)_DB.zip'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: '\\sapckb079\NETDEV\BuildsMPSS\DomainServices\$(Build.DefinitionName)\$(Build.BuildNumber)'