# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: MPSS Common

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: 'FOMS\FOMS.Api\FOMS.Api.csproj'

steps:

#- task: UseDotNet@2
#  inputs:
#    packageType: 'sdk'
#    version: '6.0.x'
#    includePreviewVersions: true

- task: InlinePowershell@1
  inputs:
    Script: |
      $file = '$(Build.SourcesDirectory)\FOMS\FOMS.Api\FOMS.Api.csproj'
      $regex = '(?<=<Version>)[^<]*'
      
      $buildVersion='$(Build.BuildNumber)'
      
      $versionFromFile = Select-String -Path $file $regex
      $versionFromFile = $versionFromFile.Matches[0].Value
      $versionFromFile = $versionFromFile.Substring(0, $versionFromFile.lastIndexOf('.'))
      
      $finalVersion = $versionFromFile + "." + $buildVersion.replace(".","")

      (Get-Content $file) -replace $regex, $finalversion | Set-Content $file

      Write-Host $finalVersion

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'C:\Users\XX_TFSAGENT_MPSS\AppData\Roaming\NuGet\NuGet.Config'
    noCache: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.BinariesDirectory)'
    noCache: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/FEAPI_$(Build.BuildNumber)_$(Build.SourceBranchName).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/FEAPI_$(Build.BuildNumber)_$(Build.SourceBranchName).zip'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: '\\sapckb079\NETDEV\BuildsMPSS\NOBY\'