# ASP.NET Core

#Default none and then overriden in the Azure Pipeline settings
trigger: none

pool:
  name: MPSS Common

variables:
  - name: runSonarQube
    value: $[or(eq(lower(variables['Build.SourceBranchName']), 'stage'), eq(lower(variables['Build.SourceBranchName']), 'production'), ne(lower(variables['USESONARQUBE']), 'false'))]
  - template: azure-pipelines-vars.yml

# custom BuildNumber
name: $(Build.DefinitionName)_$(SourceBranchName)_$(versionMajor).$(versionMinor).$(versionPatch).$(Rev:r)

steps:
- task: InlinePowershell@1
  displayName: Set Version
  inputs:
    Script: |
      $file = '$(Build.SourcesDirectory)\$(projectFile)'
      $regex = '(?<=<Version>)[^<]*'
      
      $finalVersion = "$(versionMajor).$(versionMinor).$(versionPatch)"
     
      (Get-Content $file) -replace $regex, $finalversion | Set-Content $file

      Write-Host "Final version - " -NoNewline
      Write-Host $finalVersion

- task: DotNetCoreCLI@2
  displayName: DotNet - Restore
  inputs:
    command: 'restore'
    projects: '$(projectFile)'
    feedsToUse: 'config'
    nugetConfigPath: 'C:\Users\XX_TFSAGENT_MPSS\AppData\Roaming\NuGet\NuGet.Config'
    noCache: true

- task: SonarQubePrepare@5
  condition: and(succeeded(), eq(variables.runSonarQube, true))
  inputs:
    SonarQube: 'NOBY - SonarQube'
    scannerMode: 'MSBuild'
    projectKey: 'AZURE--MPSS--CIS--OneSolution--NOBY.DS.$(Build.DefinitionName)'
    projectName: 'NOBY.DS.$(Build.DefinitionName)'
    projectVersion: '1.0.0.$(Build.BuildId)'
    extraProperties: 'sonar.verbose=true'

- task: DotNetCoreCLI@2
  displayName: DotNet - Build
  condition: and(succeeded(), eq(variables.testsFile, ''))
  inputs:
    command: 'build'
    projects: '$(projectFile)'
    arguments: '--output $(Build.BinariesDirectory)'

- task: DotNetCoreCLI@2
  displayName: DotNet - Build with tests
  condition: and(succeeded(), ne(variables.testsFile, ''))
  inputs:
    command: 'build'
    projects: '$(testsFile)'
    arguments: '--output $(Build.BinariesDirectory)'

- task: DotNetCoreCLI@2
  displayName: DotNet - Tests
  condition: and(succeeded(), ne(variables.testsFile, ''))
  inputs:
    command: test
    projects: '$(testsFile)'
    arguments: '--no-build --configuration debug'
    publishTestResults: true
    testRunTitle: '$(System.TeamProject)_$(Build.DefinitionName) on $(Build.SourceBranch)'
  env:
    ASPNETCORE_ENVIRONMENT: 'Testing'

- task: SonarQubeAnalyze@5
  condition: and(succeeded(), eq(variables.runSonarQube, true))

- task: SonarQubePublish@5
  condition: and(succeeded(), eq(variables.runSonarQube, true))
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  displayName: 'Archive Build'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build to Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: '\\sapckb079\NETDEV\BuildsMPSS\DomainServices\$(Build.DefinitionName)\$(Build.BuildNumber)'

- task: ArchiveFiles@2
  displayName: 'Archive DB Migrations'
  condition: and(succeeded(), ne(variables.dbMigrationsDirectory, ''))
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/$(dbMigrationsDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)_DB.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish DB Migrations to Artifacts'
  condition: and(succeeded(), ne(variables.dbMigrationsDirectory, ''))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)_DB.zip'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: '\\sapckb079\NETDEV\BuildsMPSS\DomainServices\$(Build.DefinitionName)\$(Build.BuildNumber)'