# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: MPSS Common

variables:
  runSonarQube: $[eq(lower(variables['USESONARQUBE']), 'true')]
  runSonarQubeByBranch: $[variables['Build.SourceBranch'] -contains "sonar"]

steps:
#- task: InlinePowershell@1
#  inputs:
#    Script: 'nslookup nodejs.org'

- task: PowerShell@2
  displayName: Display variables
  inputs:
    targetType: 'inline'
    #script: 'Write-Host "RunSonarQube: $(runSonarQube)"' 
    script: |
      # Write your PowerShell commands here.
      Write-Host "RunSonarQube: $(runSonarQube)"
      Write-Host "SourceBranchName: $(Build.SourceBranchName)"
      Write-Host "SourceBranch: $(Build.SourceBranch)"
      Write-Host "runSonarQubeByBranch: $(runSonarQubeByBranch)"
