global using MediatR;
global using Microsoft.Extensions.Logging;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using CIS.Core;
global using CIS.Infrastructure.Logging;
global using CIS.Infrastructure.Data;
global using FastEnumUtility;
