// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// 
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class MsgBoxSpecific : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""MsgBoxSpecific"",""doc"":"""",""namespace"":""cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport"",""fields"":[{""name"":""installation"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""Installation"",""doc"":""Specific instance of direct channel fat application, that is installed on specific user's device. CDM entity name(s): DirectChannelFatAppInstallation."",""namespace"":""cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport"",""fields"":[{""name"":""externalId"",""doc"":""Unique identifier of installation. CDM attribute class name: ExternalId."",""type"":{""type"":""string"",""avro.java.string"":""String"",""pattern"":""^.{0,100}$""}}]}]},{""name"":""msgAction"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""MsgAction"",""doc"":"" CDM entity name(s): MessageAction."",""namespace"":""cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport"",""fields"":[{""name"":""area"",""doc"":"" CDM attribute class name: DirectChannelMessageArea. Codebook type: CB_MsgbArea."",""default"":null,""type"":[""null"",{""type"":""string"",""avro.java.string"":""String""}]},{""name"":""platform"",""doc"":"" CDM attribute class name: DirectChannelMessagePlatform. Codebook type: CB_MsgbPlatform."",""default"":null,""type"":[""null"",{""type"":""string"",""avro.java.string"":""String""}]}]}]}]}");
		private cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport.Installation _installation;
		private cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport.MsgAction _msgAction;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MsgBoxSpecific._SCHEMA;
			}
		}
		public cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport.Installation installation
		{
			get
			{
				return this._installation;
			}
			set
			{
				this._installation = value;
			}
		}
		public cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport.MsgAction msgAction
		{
			get
			{
				return this._msgAction;
			}
			set
			{
				this._msgAction = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.installation;
			case 1: return this.msgAction;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.installation = (cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport.Installation)fieldValue; break;
			case 1: this.msgAction = (cz.kb.osbs.mcs.notificationreport.eventapi.v3.notificationreport.MsgAction)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
