// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.kb.api.mortgageservicingevents.v3.mortgageinstance
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Defines when loan can be withdrawn. CDM entity name(s): DrawdownPeriod.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class DrawdownPeriod : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""DrawdownPeriod"",""doc"":""Defines when loan can be withdrawn. CDM entity name(s): DrawdownPeriod."",""namespace"":""cz.kb.api.mortgageservicingevents.v3.mortgageinstance"",""fields"":[{""name"":""dateFrom"",""doc"":""Defines exact date when withdrawal of the loan can be started. CDM attribute class name: DrawdownPeriodDateFrom. Standard avro date represented by the number of days from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to date class in code generator (see KB Integration Platform wiki for schema registry chapter)."",""type"":{""type"":""int"",""logicalType"":""date""}},{""name"":""dateUntil"",""doc"":""Defines exact date when all purposes on the loan must be completely withdrawn. CDM attribute class name: DrawdownPeriodDateUntil. Standard avro date represented by the number of days from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to date class in code generator (see KB Integration Platform wiki for schema registry chapter)."",""default"":null,""type"":[""null"",{""type"":""int"",""logicalType"":""date""}]}]}");
		/// <summary>
		/// Defines exact date when withdrawal of the loan can be started. CDM attribute class name: DrawdownPeriodDateFrom. Standard avro date represented by the number of days from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to date class in code generator (see KB Integration Platform wiki for schema registry chapter).
		/// </summary>
		private System.DateTime _dateFrom;
		/// <summary>
		/// Defines exact date when all purposes on the loan must be completely withdrawn. CDM attribute class name: DrawdownPeriodDateUntil. Standard avro date represented by the number of days from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to date class in code generator (see KB Integration Platform wiki for schema registry chapter).
		/// </summary>
		private System.Nullable<System.DateTime> _dateUntil;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return DrawdownPeriod._SCHEMA;
			}
		}
		/// <summary>
		/// Defines exact date when withdrawal of the loan can be started. CDM attribute class name: DrawdownPeriodDateFrom. Standard avro date represented by the number of days from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to date class in code generator (see KB Integration Platform wiki for schema registry chapter).
		/// </summary>
		public System.DateTime dateFrom
		{
			get
			{
				return this._dateFrom;
			}
			set
			{
				this._dateFrom = value;
			}
		}
		/// <summary>
		/// Defines exact date when all purposes on the loan must be completely withdrawn. CDM attribute class name: DrawdownPeriodDateUntil. Standard avro date represented by the number of days from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to date class in code generator (see KB Integration Platform wiki for schema registry chapter).
		/// </summary>
		public System.Nullable<System.DateTime> dateUntil
		{
			get
			{
				return this._dateUntil;
			}
			set
			{
				this._dateUntil = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.dateFrom;
			case 1: return this.dateUntil;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.dateFrom = (System.DateTime)fieldValue; break;
			case 1: this.dateUntil = (System.Nullable<System.DateTime>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
