// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.kb.api.mortgageservicingevents.v1.mortgageinstance
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Entity representing any formal 'agreement' within any sales related area. CDM entity name(s): SalesArrangement.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class SalesArrangement : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SalesArrangement\",\"doc\":\"Entity representing any formal " +
				"\'agreement\' within any sales related area. CDM entity name(s): SalesArrangement." +
				"\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v1.mortgageinstance\",\"fields\":[" +
				"{\"name\":\"arrangementAcceptance\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"" +
				"name\":\"ArrangementAcceptance\",\"doc\":\"\'Root of\' acceptance of arrangement. I.e. c" +
				"overs all properties and relationships regarding acceptance of arrangement.Examp" +
				"le of acceptance of arrangement is signing of contract. CDM entity name(s): Arra" +
				"ngementAcceptance.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v1.mortgagein" +
				"stance\",\"fields\":[{\"name\":\"ArrangementAcceptanceByFirstApplicant\",\"type\":{\"type\"" +
				":\"record\",\"name\":\"ArrangemenAcceptanceByNaturalPerson\",\"doc\":\"Official agreement" +
				" of one party to something(e.g. agreement, application).E.g. signature of one pe" +
				"rson. CDM entity name(s): ArrangementAcceptanceByNaturalPerson.\",\"namespace\":\"cz" +
				".kb.api.mortgageservicingevents.v1.mortgageinstance\",\"fields\":[{\"name\":\"on\",\"doc" +
				"\":\"Date when party accepted the arrangement. CDM attribute class name: Arrangeme" +
				"ntAcceptanceByNaturalPersonOn. Standard avro date represented by the number of d" +
				"ays from the unix epoch, see avro specification: https://avro.apache.org/docs/1." +
				"8.0/spec.html. Consider using converters to date class in code generator (see KB" +
				" Integration Platform wiki for schema registry chapter).\",\"type\":{\"type\":\"int\",\"" +
				"logicalType\":\"date\"}}]}}]}]},{\"name\":\"salesArrangementId\",\"default\":null,\"type\":" +
				"[\"null\",{\"type\":\"record\",\"name\":\"SalesArrangementId\",\"doc\":\"Multiattribute repre" +
				"senting sales arrangement unique identifier.Multiattribute because SalesArrangem" +
				"ent is very large scope = across all product groups, ids will not be united.Seco" +
				"nd reason is existence of public id, sales arrangement identifier given to custo" +
				"mer and therefore different from internal one. CDM entity name(s): SalesArrangem" +
				"entId.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v1.mortgageinstance\",\"fie" +
				"lds\":[{\"name\":\"id\",\"doc\":\"Multi attribute identifier value itself. CDM attribute" +
				" class name: SalesArrangementIdId. Attribute has simple type ST_IdString100Defau" +
				"lt with description: Standard data type to be used as ID, i.e. unique identifier" +
				". Longer vevrsion - 100 characters. It is not supposed to be human-readable.E.g." +
				": AgreementID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"pattern\":\"^." +
				"{0,100}$\"}}]}]}]}");
		private cz.kb.api.mortgageservicingevents.v1.mortgageinstance.ArrangementAcceptance _arrangementAcceptance;
		private cz.kb.api.mortgageservicingevents.v1.mortgageinstance.SalesArrangementId _salesArrangementId;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SalesArrangement._SCHEMA;
			}
		}
		public cz.kb.api.mortgageservicingevents.v1.mortgageinstance.ArrangementAcceptance arrangementAcceptance
		{
			get
			{
				return this._arrangementAcceptance;
			}
			set
			{
				this._arrangementAcceptance = value;
			}
		}
		public cz.kb.api.mortgageservicingevents.v1.mortgageinstance.SalesArrangementId salesArrangementId
		{
			get
			{
				return this._salesArrangementId;
			}
			set
			{
				this._salesArrangementId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.arrangementAcceptance;
			case 1: return this.salesArrangementId;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.arrangementAcceptance = (cz.kb.api.mortgageservicingevents.v1.mortgageinstance.ArrangementAcceptance)fieldValue; break;
			case 1: this.salesArrangementId = (cz.kb.api.mortgageservicingevents.v1.mortgageinstance.SalesArrangementId)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
