USE [master]
GO

/****** Object:  Database [CustomerService]    Script Date: 05.04.2022 19:23:00 ******/
CREATE DATABASE [CustomerService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomerService', FILENAME = N'F:\MSSQL15.UAT1\MSSQL\DATA\CustomerService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomerService_log', FILENAME = N'G:\MSSQL15.UAT1\MSSQL\Data\CustomerService_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomerService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomerService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomerService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomerService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomerService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomerService] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomerService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CustomerService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomerService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomerService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomerService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomerService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomerService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomerService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomerService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomerService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CustomerService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomerService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomerService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomerService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomerService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomerService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomerService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomerService] SET RECOVERY FULL 
GO

ALTER DATABASE [CustomerService] SET  MULTI_USER 
GO

ALTER DATABASE [CustomerService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomerService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomerService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomerService] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomerService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomerService] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CustomerService] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CustomerService] SET  READ_WRITE 
GO


