USE [master]
GO

/****** Object:  Database [RealEstateValuation]    Script Date: 04.04.2022 19:29:39 ******/
CREATE DATABASE [RealEstateValuation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RealEstateValuation', FILENAME = N'F:\MSSQL15.MSSQLSERVER\MSSQL\DATA\RealEstateValuation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RealEstateValuation', FILENAME = N'G:\MSSQL15.MSSQLSERVER\MSSQL\Data\RealEstateValuation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RealEstateValuation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RealEstateValuation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RealEstateValuation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RealEstateValuation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RealEstateValuation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RealEstateValuation] SET ARITHABORT OFF 
GO

ALTER DATABASE [RealEstateValuation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RealEstateValuation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RealEstateValuation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RealEstateValuation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RealEstateValuation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RealEstateValuation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RealEstateValuation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RealEstateValuation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RealEstateValuation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RealEstateValuation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RealEstateValuation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RealEstateValuation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RealEstateValuation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RealEstateValuation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RealEstateValuation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RealEstateValuation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RealEstateValuation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RealEstateValuation] SET RECOVERY FULL 
GO

ALTER DATABASE [RealEstateValuation] SET  MULTI_USER 
GO

ALTER DATABASE [RealEstateValuation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RealEstateValuation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RealEstateValuation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RealEstateValuation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RealEstateValuation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RealEstateValuation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RealEstateValuation] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RealEstateValuation] SET  READ_WRITE 
GO


