DROP TABLE IF EXISTS [dbo].[ServiceDiscovery]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ServiceDiscovery](
	[EnvironmentName] [varchar](50) NOT NULL,
	[ServiceName] [varchar](50) NOT NULL,
	[ServiceUrl] [varchar](250) NOT NULL,
	[ServiceType] [tinyint] NOT NULL,
 CONSTRAINT [PK_ServiceDiscovery] PRIMARY KEY CLUSTERED 
(
	[ServiceName] ASC,
	[ServiceType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
