// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.kb.api.mortgageservicingevents.v3
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Změny na produktu hypoteky. Schema belongs to API MortgageServicingEvents.v3. Root type description: General entity for any event. CDM entity name(s): Event.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class MortgageInstanceChanged : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"MortgageInstanceChanged\",\"doc\":\"Změny na produktu hypote" +
				"ky. Schema belongs to API MortgageServicingEvents.v3. Root type description: Gen" +
				"eral entity for any event. CDM entity name(s): Event.\",\"namespace\":\"cz.kb.api.mo" +
				"rtgageservicingevents.v3\",\"fields\":[{\"name\":\"eventId\",\"doc\":\"Unique identifier o" +
				"f event. CDM attribute class name: EventId. Attribute has simple type ST_String1" +
				"00 with description: General string of max length 100.\",\"type\":{\"type\":\"string\"," +
				"\"avro.java.string\":\"String\",\"pattern\":\"^.{0,100}$\"}},{\"name\":\"New\",\"type\":{\"type" +
				"\":\"record\",\"name\":\"MortgageInstance\",\"doc\":\"Specialization of product instance f" +
				"or consumer loan business product.. ## Mortgage product instance. CDM entity nam" +
				"e(s): ConsumerLoanInstance,MortgageInstance.\",\"namespace\":\"cz.kb.api.mortgageser" +
				"vicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"activeExactlyFrom\",\"doc\":\"D" +
				"ate from which the item is active#CZ#Datum od ktereho je polozka aktivni.  CDM a" +
				"ttribute class name: ActiveExactlyFrom. Standard avro dateTime represented by th" +
				"e number of milliseconds from the unix epoch, see avro specification: https://av" +
				"ro.apache.org/docs/1.8.0/spec.html. Consider using converters to dateTime class " +
				"in code generator (see KB Integration Platform wiki for schema registry chapter)" +
				".\",\"default\":null,\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"" +
				"}]},{\"name\":\"agreement\",\"type\":{\"type\":\"record\",\"name\":\"Agreement\",\"doc\":\"\'Obcho" +
				"d\'Agreement is performing sale to customer. Agreement contains product, service " +
				"instances, product offer and context required. Agreement is only present during " +
				"sale action (selling, modification or closing  of product or service instances. " +
				"There is no agreement in presales..#CZ#Obchod zprostredkovava prodej zakaznikovi" +
				". Obchod obsahuje produkt, instanci sluzby, nabidku produktu a pozadovany kontex" +
				"t. O obchodu je mozne mluvit pouze v pripade akce predeje (prodej, zmena nebo uz" +
				"avreni produktu, potazmo instance sluzby). O obchodu se neda mluvit v pripade pr" +
				"edprodeje. CDM entity name(s): Agreement.\",\"namespace\":\"cz.kb.api.mortgageservic" +
				"ingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"agreementApproval\",\"default\":n" +
				"ull,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Approval\",\"doc\":\"General entity repr" +
				"esenting approval process E.g. agreement or exception approval. CDM entity name(" +
				"s): Approval.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstanc" +
				"e\",\"fields\":[{\"name\":\"on\",\"doc\":\"Time when overall approval was made. CDM attrib" +
				"ute class name: ApprovalOn. Standard avro dateTime represented by the number of " +
				"milliseconds from the unix epoch, see avro specification: https://avro.apache.or" +
				"g/docs/1.8.0/spec.html. Consider using converters to dateTime class in code gene" +
				"rator (see KB Integration Platform wiki for schema registry chapter).\",\"default\"" +
				":null,\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]},{\"name\":" +
				"\"requestedOn\",\"doc\":\"Time when overall approval was requested. CDM attribute cla" +
				"ss name: ApprovalRequestedOn. Standard avro dateTime represented by the number o" +
				"f milliseconds from the unix epoch, see avro specification: https://avro.apache." +
				"org/docs/1.8.0/spec.html. Consider using converters to dateTime class in code ge" +
				"nerator (see KB Integration Platform wiki for schema registry chapter).\",\"type\":" +
				"{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}]}]}},{\"name\":\"ApplicationSal" +
				"esArrangement\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"SalesArran" +
				"gement\",\"doc\":\"Entity representing any formal \'agreement\' within any sales relat" +
				"ed area. CDM entity name(s): SalesArrangement.\",\"namespace\":\"cz.kb.api.mortgages" +
				"ervicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"arrangementAcceptance\",\"d" +
				"efault\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ArrangementAcceptance\",\"doc" +
				"\":\"\'Root of\' acceptance of arrangement. I.e. covers all properties and relations" +
				"hips regarding acceptance of arrangement.Example of acceptance of arrangement is" +
				" signing of contract. CDM entity name(s): ArrangementAcceptance.\",\"namespace\":\"c" +
				"z.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"Arrange" +
				"mentAcceptanceByFirstApplicant\",\"type\":{\"type\":\"record\",\"name\":\"ArrangemenAccept" +
				"anceByNaturalPerson\",\"doc\":\"Official agreement of one party to something(e.g. ag" +
				"reement, application).E.g. signature of one person. CDM entity name(s): Arrangem" +
				"entAcceptanceByNaturalPerson.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3" +
				".mortgageinstance\",\"fields\":[{\"name\":\"on\",\"doc\":\"Date when party accepted the ar" +
				"rangement. CDM attribute class name: ArrangementAcceptanceByNaturalPersonOn. Sta" +
				"ndard avro date represented by the number of days from the unix epoch, see avro " +
				"specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using conv" +
				"erters to date class in code generator (see KB Integration Platform wiki for sch" +
				"ema registry chapter).\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}}]}]},{\"nam" +
				"e\":\"salesArrangementId\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"S" +
				"alesArrangementId\",\"doc\":\"Multiattribute representing sales arrangement unique i" +
				"dentifier.Multiattribute because SalesArrangement is very large scope = across a" +
				"ll product groups, ids will not be united.Second reason is existence of public i" +
				"d, sales arrangement identifier given to customer and therefore different from i" +
				"nternal one. CDM entity name(s): SalesArrangementId.\",\"namespace\":\"cz.kb.api.mor" +
				"tgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"id\",\"doc\":\"Multi at" +
				"tribute identifier value itself. CDM attribute class name: SalesArrangementIdId." +
				" Attribute has simple type ST_IdString100Default with description: Standard data" +
				" type to be used as ID, i.e. unique identifier. Longer vevrsion - 100 characters" +
				". It is not supposed to be human-readable.E.g.: AgreementID\",\"type\":{\"type\":\"str" +
				"ing\",\"avro.java.string\":\"String\",\"pattern\":\"^.{0,100}$\"}}]}]}]}]},{\"name\":\"Contr" +
				"actSalesArrangement\",\"type\":{\"type\":\"record\",\"name\":\"ContractSalesArrangement\",\"" +
				"doc\":\"Entity representing any formal \'agreement\' within any sales related area. " +
				"CDM entity name(s): SalesArrangement.\",\"namespace\":\"cz.kb.api.mortgageservicinge" +
				"vents.v3.mortgageinstance\",\"fields\":[{\"name\":\"ArrangementAcceptance\",\"type\":{\"ty" +
				"pe\":\"record\",\"name\":\"ContractArrangementAcceptance\",\"doc\":\"\'Root of\' acceptance " +
				"of arrangement. I.e. covers all properties and relationships regarding acceptanc" +
				"e of arrangement.Example of acceptance of arrangement is signing of contract. CD" +
				"M entity name(s): ArrangementAcceptance.\",\"namespace\":\"cz.kb.api.mortgageservici" +
				"ngevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"on\",\"doc\":\"Date when overall as" +
				"sent was reached. CDM attribute class name: ArrangementAcceptanceOn. Standard av" +
				"ro date represented by the number of days from the unix epoch, see avro specific" +
				"ation: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters t" +
				"o date class in code generator (see KB Integration Platform wiki for schema regi" +
				"stry chapter).\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}},{\"name\":\"salesArr" +
				"angementId\",\"type\":{\"type\":\"record\",\"name\":\"ContractSalesArrangementId\",\"doc\":\"M" +
				"ultiattribute representing sales arrangement unique identifier.Multiattribute be" +
				"cause SalesArrangement is very large scope = across all product groups, ids will" +
				" not be united.Second reason is existence of public id, sales arrangement identi" +
				"fier given to customer and therefore different from internal one. CDM entity nam" +
				"e(s): SalesArrangementId.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mor" +
				"tgageinstance\",\"fields\":[{\"name\":\"id\",\"doc\":\"Multi attribute identifier value it" +
				"self. CDM attribute class name: SalesArrangementIdId. Attribute has simple type " +
				"ST_IdString100Default with description: Standard data type to be used as ID, i.e" +
				". unique identifier. Longer vevrsion - 100 characters. It is not supposed to be " +
				"human-readable.E.g.: AgreementID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"St" +
				"ring\",\"pattern\":\"^.{0,100}$\"}}]}}]}},{\"name\":\"FinalLoanWithdrawal\",\"default\":nul" +
				"l,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"LoanWithdrawal\",\"doc\":\"One withdrawal " +
				"from one sold loan\'s purpose.. ## Request for withdrawals (not necessarily by cu" +
				"stomer). CDM entity name(s): LoanWithdrawal,WithdrawalRequest.\",\"namespace\":\"cz." +
				"kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"date\",\"do" +
				"c\":\"Depends on state it has meaning: Planned date of withdrawal/ Date of perform" +
				"ed withdrawal. CDM attribute class name: LoanWithdrawalDate. Standard avro dateT" +
				"ime represented by the number of milliseconds from the unix epoch, see avro spec" +
				"ification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converte" +
				"rs to dateTime class in code generator (see KB Integration Platform wiki for sch" +
				"ema registry chapter).\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}" +
				"]}]},{\"name\":\"FirstLoanWithdrawal\",\"default\":null,\"type\":[\"null\",\"LoanWithdrawal" +
				"\"]},{\"name\":\"instanceState\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name" +
				"\":\"InstanceState\",\"doc\":\"State of any marketable item instance (agreement, produ" +
				"ct instance, service instance,...).#CZ#Stav instance jakekoliv prodejne polozky " +
				"(obchod, instance produktu, instance sluzby...). CDM entity name(s): InstanceSta" +
				"te.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields" +
				"\":[{\"name\":\"instanceStateCode\",\"type\":{\"type\":\"record\",\"name\":\"InstanceStateCode" +
				"\",\"doc\":\"Multicodebook property of marketable item instance state (agreement, pr" +
				"oduct instance, service instance,...) identifier.It is multicodebook because sta" +
				"te is generic property and individual product/agreements/... have individually d" +
				"efined state machines.#CZ#Vicehodnotova ciselnikova promenna identifikatoru stav" +
				"u predejnych polozek (obchod, instance produktu, instance sluzby...). Jedna se o" +
				" vicehodnotou ciselnikovou promenou, protoze stav je obecna promenna. Ta ma indi" +
				"vidualne definovane stavy v zavislosti na tom, zda jde o obchod, produkt... . CD" +
				"M entity name(s): InstanceStateCode.\",\"namespace\":\"cz.kb.api.mortgageservicingev" +
				"ents.v3.mortgageinstance\",\"fields\":[{\"name\":\"state\",\"doc\":\"Codebook value of sta" +
				"te itself.#CZ#Vlastni ciselnikova hodnota stavu. Attribute has specific codebook" +
				" type: CB_MortgageLifeCyclePhase. CDM attribute class name: InstanceStateCodeSta" +
				"te. Attribute has simple type CB_MultiCodebookValue with description: Represents" +
				" information that value can be from more than one codebook. Codebook type: CB_Mo" +
				"rtgageLifeCyclePhase.\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"patt" +
				"ern\":\"^.{0,100}$\"}}]}}]}]},{\"name\":\"LastLoanWithdrawal\",\"default\":null,\"type\":[\"" +
				"null\",\"LoanWithdrawal\"]},{\"name\":\"LifeCycleInstanceState\",\"default\":null,\"type\":" +
				"[\"null\",\"InstanceState\"]},{\"name\":\"LoanAccount\",\"type\":{\"type\":\"record\",\"name\":\"" +
				"Account\",\"doc\":\"This entity represents information about account as is used in p" +
				"ayment landscape. For example has properties current balance, account number, ib" +
				"an, currency, available balance,.. . If this entity represents multicurrency (MC" +
				"Y) master account (multicurrency=true):: the account is called master (parent) a" +
				"ccount; it acts as envelope for supported currencies subaccounts set; balances a" +
				"nd limits attributes represent aggregated values from the currencies subaccounts" +
				" (converted to base currency); currency represents base (nominated) currency of " +
				"master account.; payment domain systems work only with master account informatio" +
				"n or identification (single master account number plus currency); transactions, " +
				"holds and interests occure only on specific currency subaccounts.;To be deleted:" +
				"In KB finance called \'aplikacni ucet\'.This is not product sales entity. Do not c" +
				"onfuse with CurrentAccountProduct. Also do not represents general ledger account" +
				"s.. ## A representation of a product instance as implemented in bank\'s core syst" +
				"ems, systems delivering product\'s functionality to customer. CDM entity name(s):" +
				" Account,TechnicalItemInstance.\",\"namespace\":\"cz.kb.api.mortgageservicingevents." +
				"v3.mortgageinstance\",\"fields\":[{\"name\":\"accountNumber\",\"type\":{\"type\":\"record\",\"" +
				"name\":\"AccountNumber\",\"doc\":\"AccountNumber: .AccountNumberPrefix; .AccountNumber" +
				"Core; .AccountNumberBankCode; .AccountNumberIban;. ## IBAN (International Bank A" +
				"ccount Number) representation of the account number by ISO 13616 - for detail de" +
				"scription see attribute notes. ## Account identification number defined by CNB f" +
				"or domestic paymentshttps://www.cnb.cz/export/sites/cnb/cs/legislativa/.gallerie" +
				"s/vyhlasky/vyhlaska_169_2011.pdf. CDM entity name(s): AccountNumberIBAN,AccountN" +
				"umberCNB.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"" +
				"fields\":[{\"name\":\"bankCode\",\"doc\":\"Bank code: 4 digits; contains values from \'Di" +
				"rectory of payment system codes\' by CNB (https://www.cnb.cz/en/payments/accounts" +
				"-bank-codes/); e.g.: for \'1234-567890/0100\' the bank code is \'0100\';. CDM attrib" +
				"ute class name: AccountNumberCNBBankCode. Attribute has simple type ST_BankCode " +
				"with description: Kod banky.\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String" +
				"\",\"pattern\":\"^.{0,4}$\"}},{\"name\":\"core\",\"doc\":\"Core/base of account number (i.e." +
				" the number without the bank code and without prefix): 2 to 10 digits; mandatory" +
				"; e.g.: for \'1234-567890/0100\' the core is \'567890\';. CDM attribute class name: " +
				"AccountNumberCNBCore. Attribute has simple type ST_AccountNumberCore with descri" +
				"ption: Cislo uctu bez prefixu.An account number excluding a prefix.\",\"type\":{\"ty" +
				"pe\":\"string\",\"avro.java.string\":\"String\",\"pattern\":\"0*[1-9][0-9]*[1-9][0-9]*\"}}," +
				"{\"name\":\"iban\",\"doc\":\"IBAN representation of the account number: up to 32 charac" +
				"ters - XX## #### #### #### #### #### #### ####; first 2 characters - country cod" +
				"e; next 2 characters are check digits; rest is country dependent - for CZ&amp;SK" +
				" - 4 digits bank code, 6 digits prefix, 10 digits core/base account number; with" +
				"out blanks for electronic communication; grouped by 4 characters for user interf" +
				"aces;. CDM attribute class name: AccountNumberIBANIban. Attribute has simple typ" +
				"e ST_IBAN with description: The International Bank Account Number (IBAN).\",\"type" +
				"\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"pattern\":\"[A-Z][A-Z][0-9][0-9][0" +
				"-9A-Z]*\"}},{\"name\":\"prefix\",\"doc\":\"Account number prefix: up to 6 digits; option" +
				"al - could be empty or contain zeroes \'000000\'; e.g.: for \'1234-567890/0100\' the" +
				" prefix is \'1234\';. CDM attribute class name: AccountNumberCNBPrefix. Attribute " +
				"has simple type ST_AccountNumberPrefix with description: Cislo uctu prefix.An ac" +
				"count number prefix. \",\"default\":null,\"type\":[\"null\",{\"type\":\"string\",\"avro.java" +
				".string\":\"String\",\"pattern\":\"[0-9]*\"}]}]}},{\"name\":\"AccountState\",\"default\":null" +
				",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"TechnicalItemInstanceState\",\"doc\":\"Mult" +
				"icodebook property of technical product instance state. As the name suggests, it" +
				" defines state of product instance in its core system.It is multicodebook as sta" +
				"te of technical product instance is generic concept and will differ across techn" +
				"ical product instance core systems. CDM entity name(s): TechnicalItemInstanceSta" +
				"te.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields" +
				"\":[{\"name\":\"class\",\"doc\":\"Attribute that defines codebook that is used in attrib" +
				"ute state. CDM attribute class name: TechnicalItemInstanceStateClass. Codebook t" +
				"ype: CB_TechnicalProductInstanceStateClass.\",\"type\":{\"type\":\"string\",\"avro.java." +
				"string\":\"String\"}},{\"name\":\"state\",\"doc\":\"Multicodebook value of state itself. A" +
				"ttribute has specific codebook type: CB_Undefined. CDM attribute class name: Tec" +
				"hnicalItemInstanceStateState. Attribute has simple type CB_MultiCodebookValue wi" +
				"th description: Represents information that value can be from more than one code" +
				"book. Codebook type: CB_Undefined.\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"" +
				"String\",\"pattern\":\"^.{0,100}$\"}}]}]}]}},{\"name\":\"loanAmount\",\"type\":{\"type\":\"rec" +
				"ord\",\"name\":\"LoanAmount\",\"doc\":\"Vyska uveruInformation about loan amount. This i" +
				"s static information. Change only with sale or maintenance action. CDM entity na" +
				"me(s): LoanAmount.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgagein" +
				"stance\",\"fields\":[{\"name\":\"limit\",\"doc\":\"Vyska uveru, ktora bola schvalena. (Poz" +
				"or, nie je nutne suma, ktoru si klient skutocne poziacia)Allowed loan limit. It " +
				"is maximum amount that customer can borrow from bank.E.g. credit card limit, ove" +
				"rdraft limit, or contracted consumer loan amount. CDM attribute class name: Loan" +
				"AmountLimit. Attribute has simple type ST_AmountMoney with description: Castka.D" +
				"ecimal number representing an amount of money.\",\"type\":{\"type\":\"bytes\",\"logicalT" +
				"ype\":\"decimal\",\"precision\":17,\"scale\":2}}]}},{\"name\":\"loanBalance\",\"type\":{\"type" +
				"\":\"record\",\"name\":\"LoanBalance\",\"doc\":\"Information entity with various loan/cred" +
				"it balance information on given date.. CDM entity name(s): LoanBalance.\",\"namesp" +
				"ace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"" +
				"amountNotYetWithdrawn\",\"doc\":\"Amount money that was not yet withdrawn from this " +
				"loan. CDM attribute class name: LoanBalanceAmountNotYetWithdrawn. Attribute has " +
				"simple type ST_AmountMoney with description: Castka.Decimal number representing " +
				"an amount of money.\",\"default\":null,\"type\":[\"null\",{\"type\":\"bytes\",\"logicalType\"" +
				":\"decimal\",\"precision\":17,\"scale\":2}]},{\"name\":\"amountWithdrawn\",\"doc\":\"Amount m" +
				"oney that was already withdrawn from this loan. CDM attribute class name: LoanBa" +
				"lanceAmountWithdrawn. Attribute has simple type ST_AmountMoney with description:" +
				" Castka.Decimal number representing an amount of money.\",\"default\":null,\"type\":[" +
				"\"null\",{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":17,\"scale\":2}]},{\"nam" +
				"e\":\"interestAmount\",\"doc\":\"Actual interest amount to be paid. CDM attribute clas" +
				"s name: LoanBalanceInterestAmount. Attribute has simple type ST_AmountMoney with" +
				" description: Castka.Decimal number representing an amount of money.\",\"default\":" +
				"null,\"type\":[\"null\",{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":17,\"scal" +
				"e\":2}]},{\"name\":\"lateFee\",\"doc\":\"All non_standard=late yet unpaid fees related t" +
				"o loan soldproduct. (additional fees, fees for late repayment of installment). C" +
				"DM attribute class name: LoanBalanceLateFee. Attribute has simple type ST_Amount" +
				"Money with description: Castka.Decimal number representing an amount of money.\"," +
				"\"default\":null,\"type\":[\"null\",{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision" +
				"\":17,\"scale\":2}]},{\"name\":\"loanFee\",\"doc\":\"All standard yet unpaid fees related " +
				"to this loan soldproduct. CDM attribute class name: LoanBalanceLoanFee. Attribut" +
				"e has simple type ST_AmountMoney with description: Castka.Decimal number represe" +
				"nting an amount of money.\",\"default\":null,\"type\":[\"null\",{\"type\":\"bytes\",\"logica" +
				"lType\":\"decimal\",\"precision\":17,\"scale\":2}]},{\"name\":\"overdueInstallmentAmount\"," +
				"\"doc\":\"Sum of overdue installments amount.Has to be disputed!!. CDM attribute cl" +
				"ass name: LoanBalanceOverdueInstallmentAmount. Attribute has simple type ST_Amou" +
				"ntMoney with description: Castka.Decimal number representing an amount of money." +
				"\",\"default\":null,\"type\":[\"null\",{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precisi" +
				"on\":17,\"scale\":2}]},{\"name\":\"principalAmount\",\"doc\":\"Actual (not yet repaid) pri" +
				"ncipal amount. Relevant for loans. CDM attribute class name: LoanBalancePrincipa" +
				"lAmount. Attribute has simple type ST_AmountMoney with description: Castka.Decim" +
				"al number representing an amount of money.\",\"default\":null,\"type\":[\"null\",{\"type" +
				"\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":17,\"scale\":2}]},{\"name\":\"totalAmou" +
				"nt\",\"doc\":\"If loan was to be completely repaid at this time, this is total amoun" +
				"t that would be needed. CDM attribute class name: LoanBalanceTotalAmount. Attrib" +
				"ute has simple type ST_AmountMoney with description: Castka.Decimal number repre" +
				"senting an amount of money.\",\"default\":null,\"type\":[\"null\",{\"type\":\"bytes\",\"logi" +
				"calType\":\"decimal\",\"precision\":17,\"scale\":2}]},{\"name\":\"totalAmountWithoutUncred" +
				"itedInterest\",\"doc\":\".If loan was to be completely repaid at this time, this is " +
				"total amount that would be needed. CDM attribute class name: LoanBalanceTotalAmo" +
				"unt. Attribute has simple type ST_AmountMoney with description: Castka.Decimal n" +
				"umber representing an amount of money.\",\"default\":null,\"type\":[\"null\",{\"type\":\"b" +
				"ytes\",\"logicalType\":\"decimal\",\"precision\":17,\"scale\":2}]}]}},{\"name\":\"loanInstan" +
				"ceInfo\",\"type\":{\"type\":\"record\",\"name\":\"LoanInstanceInfo\",\"doc\":\"Information ent" +
				"ity representing any loan product (instance of product). CDM entity name(s): Loa" +
				"nInstanceInfo.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstan" +
				"ce\",\"fields\":[{\"name\":\"ExpectedDrawdownPeriod\",\"type\":{\"type\":\"record\",\"name\":\"D" +
				"rawdownPeriod\",\"doc\":\"Defines when loan can be withdrawn. CDM entity name(s): Dr" +
				"awdownPeriod.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstanc" +
				"e\",\"fields\":[{\"name\":\"dateFrom\",\"doc\":\"Defines exact date when withdrawal of the" +
				" loan can be started. CDM attribute class name: DrawdownPeriodDateFrom. Standard" +
				" avro date represented by the number of days from the unix epoch, see avro speci" +
				"fication: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converter" +
				"s to date class in code generator (see KB Integration Platform wiki for schema r" +
				"egistry chapter).\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"dateUnti" +
				"l\",\"doc\":\"Defines exact date when all purposes on the loan must be completely wi" +
				"thdrawn. CDM attribute class name: DrawdownPeriodDateUntil. Standard avro date r" +
				"epresented by the number of days from the unix epoch, see avro specification: ht" +
				"tps://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to date cl" +
				"ass in code generator (see KB Integration Platform wiki for schema registry chap" +
				"ter).\",\"default\":null,\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}]}]}},{\"" +
				"name\":\"loanInstallments\",\"type\":{\"type\":\"record\",\"name\":\"LoanInstallments\",\"doc\"" +
				":\"One installment amount. It is information entity. It can be used for any insta" +
				"llment. CDM entity name(s): LoanInstallments.\",\"namespace\":\"cz.kb.api.mortgagese" +
				"rvicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"dayInMonth\",\"doc\":\"Day wit" +
				"hin month when installment is due to be paid. CDM attribute class name: LoanInst" +
				"allmentsDayInMonth. Codebook type: CB_DayOfMonth.\",\"type\":{\"type\":\"string\",\"avro" +
				".java.string\":\"String\"}},{\"name\":\"firstAnnuityLoanIndividualInstallment\",\"defaul" +
				"t\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"FirstAnnuityLoanIndividualInstal" +
				"lment\",\"doc\":\"Individual/concrete repayment of loan - one loan installment. CDM " +
				"entity name(s): LoanIndividualInstallment.\",\"namespace\":\"cz.kb.api.mortgageservi" +
				"cingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"on\",\"doc\":\"Date of installmen" +
				"t to be repaid/was repaid. CDM attribute class name: LoanIndividualInstallmentOn" +
				". Standard avro date represented by the number of days from the unix epoch, see " +
				"avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using" +
				" converters to date class in code generator (see KB Integration Platform wiki fo" +
				"r schema registry chapter).\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}]},{\"n" +
				"ame\":\"loanIndividualInstallment\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\"," +
				"\"name\":\"LoanIndividualInstallment\",\"doc\":\"Individual/concrete repayment of loan " +
				"- one loan installment. CDM entity name(s): LoanIndividualInstallment.\",\"namespa" +
				"ce\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"a" +
				"mount\",\"doc\":\"Total amount that has to paid as one loan installment. CDM attribu" +
				"te class name: LoanIndividualInstallmentAmount. Attribute has simple type ST_Amo" +
				"untMoney with description: Castka.Decimal number representing an amount of money" +
				".\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":17,\"scale\":2}}]}]}" +
				",{\"name\":\"nextLoanIndividualInstallment\",\"default\":null,\"type\":[\"null\",{\"type\":\"" +
				"record\",\"name\":\"NextLoanIndividualInstallment\",\"doc\":\"Individual/concrete repaym" +
				"ent of loan - one loan installment. CDM entity name(s): LoanIndividualInstallmen" +
				"t.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\"" +
				":[{\"name\":\"on\",\"doc\":\"Date of installment to be repaid/was repaid. CDM attribute" +
				" class name: LoanIndividualInstallmentOn. Standard avro date represented by the " +
				"number of days from the unix epoch, see avro specification: https://avro.apache." +
				"org/docs/1.8.0/spec.html. Consider using converters to date class in code genera" +
				"tor (see KB Integration Platform wiki for schema registry chapter).\",\"type\":{\"ty" +
				"pe\":\"int\",\"logicalType\":\"date\"}}]}]}]}},{\"name\":\"loanMaturity\",\"default\":null,\"t" +
				"ype\":[\"null\",{\"type\":\"record\",\"name\":\"LoanMaturity\",\"doc\":\"SplatnostBasic inform" +
				"ation about loan maturity. More detailed information are in PaymentSchedule. CDM" +
				" entity name(s): LoanMaturity.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v" +
				"3.mortgageinstance\",\"fields\":[{\"name\":\"on\",\"doc\":\"Date when loan will be repaid " +
				"under normal circumstances. CDM attribute class name: LoanMaturityOn. Standard a" +
				"vro date represented by the number of days from the unix epoch, see avro specifi" +
				"cation: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters " +
				"to date class in code generator (see KB Integration Platform wiki for schema reg" +
				"istry chapter).\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}]}]}},{\"name\":\"loa" +
				"nInterestRate\",\"type\":{\"type\":\"record\",\"name\":\"LoanInterestRate\",\"doc\":\"Specific" +
				" interest rate of proposed or sold loan business product. This is only THE (prim" +
				"ary) interest rate. This is NOT any other interest rate on product. CDM entity n" +
				"ame(s): LoanInterestRate.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mor" +
				"tgageinstance\",\"fields\":[{\"name\":\"fixedRatePeriod\",\"default\":null,\"type\":[\"null\"" +
				",{\"type\":\"record\",\"name\":\"FixedRatePeriod\",\"doc\":\"Time that interest rate is fix" +
				"ed and can not change. CDM entity name(s): FixedRatePeriod.\",\"namespace\":\"cz.kb." +
				"api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"nextRefixDat" +
				"e\",\"doc\":\".Date, when the next fixed period of the loan (mortgage) has to be def" +
				"ined.Datum pristi refixace urokove sazby uveru (hypoteky). CDM attribute class n" +
				"ame: FixedRatePeriodNextRefixDate. Standard avro date represented by the number " +
				"of days from the unix epoch, see avro specification: https://avro.apache.org/doc" +
				"s/1.8.0/spec.html. Consider using converters to date class in code generator (se" +
				"e KB Integration Platform wiki for schema registry chapter).\",\"default\":null,\"ty" +
				"pe\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}]},{\"name\":\"period\",\"doc\":\"Total " +
				"length of period in units. If no units are given, default is month. CDM attribut" +
				"e class name: FixedRatePeriodPeriod. Attribute has simple type ST_PositiveInt wi" +
				"th description: Integer with a constraint. The value must be a positive number, " +
				"i.e. zero is excluded.\",\"type\":\"int\"}]}]},{\"name\":\"value\",\"doc\":\"Resulting inter" +
				"est rate, i.e. what customer sees.Urokova mira uveru.(High level) vbs + srn + ma" +
				"rgin. CDM attribute class name: LoanInterestRateValue. Attribute has simple type" +
				" ST_InterestRate with description: Urok.Represents an interest rate or its part," +
				" (Interest rate, SRN, Margin).E. g. 1.0 (=100%), 0.25 (=25%)Limited at 100000%\"," +
				"\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":11,\"scale\":8}}]}},{\"n" +
				"ame\":\"mktItemInstanceInfo\",\"type\":{\"type\":\"record\",\"name\":\"MktItemInstanceInfo\"," +
				"\"doc\":\"Information entity. Entity that is used to provide information about any " +
				"instance of marketable item (product, service, frame agreement, bundle,...). CDM" +
				" entity name(s): MktItemInstanceInfo.\",\"namespace\":\"cz.kb.api.mortgageservicinge" +
				"vents.v3.mortgageinstance\",\"fields\":[{\"name\":\"catalogueMktItemInOfferSpecsInfo\"," +
				"\"type\":{\"type\":\"record\",\"name\":\"CatalogueMktItemInOfferSpecsInfo\",\"doc\":\"Informa" +
				"tion about catalogue specification of business product in offer.catalogue = no s" +
				"ituation/context available, i.e. generic definition of product.  CDM entity name" +
				"(s): CatalogueMktItemInOfferSpecsInfo.\",\"namespace\":\"cz.kb.api.mortgageservicing" +
				"events.v3.mortgageinstance\",\"fields\":[{\"name\":\"catalogueItemObjectCode\",\"type\":{" +
				"\"type\":\"record\",\"name\":\"CatalogueItemObjectCode\",\"doc\":\"Multiattribute property " +
				"of any catalog item identification (product, service, offer...). The identifier " +
				"(object code) does not change when the version changes Multi-attribute is used b" +
				"ecause there is not only one identification of the bank\'s product items (product" +
				"s, services), but there can be several.#CZ#Multiatributova vlastnost jakekoli id" +
				"entifikace katalogove polozky (produktu, sluzby, nabidky...). Identifikator (obj" +
				"ect code) se nemeni pri zmene verze Vice atributu je pouzito z duvodu ze neexist" +
				"uje pouze jedina identifikace produktovych polozek banky (produktu, sluzeb), ale" +
				" muze jich byt vice. CDM entity name(s): CatalogueItemObjectCode.\",\"namespace\":\"" +
				"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"object" +
				"Code\",\"doc\":\"The identifier of the catalog item (product, service, offering, etc" +
				".) that does not change when the version of the item changes.For example, the St" +
				"andard Tariff Offer has different settings in different versions (e.g. different" +
				" types and quantities of products included), these versions have different IDs b" +
				"ut the same OC as long as it is still the same offer from the bank\'s point of vi" +
				"ew.#CZ#Identifikator katalogve polozky (produkt, sluzba, nabidka apod.), ktery s" +
				"e nemeni pri zmene verze polozky.Napr. Nabidka tarifu Standard ma v ruznych verz" +
				"ich ruzna nastaveni (napr. ruzne typy a mnozstvi produktu v ni zahrnute), tyto v" +
				"erze maji odlisne ID, ale stejny OC, dokud se jedna z pohledu banky o stale stej" +
				"nou nabidku. CDM attribute class name: CatalogueItemObjectCodeObjectCode. Attrib" +
				"ute has simple type ST_CodeDefault with description: Standard data type to be us" +
				"ed on *Code* attributes.\'Code\' is very similar to \'ID\' (i.e. unique identifier) " +
				"but it is supposed to be human-readable.E.g. SystemApplicationCode, ProductGroup" +
				"Code.\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"pattern\":\"^.{0,100}$" +
				"\"}}]}}]}},{\"name\":\"partyInMktItemInstanceInfoes\",\"type\":{\"type\":\"array\",\"items\":" +
				"{\"type\":\"record\",\"name\":\"PartyInMktItemInstanceInfo\",\"doc\":\"Information entity. " +
				"Describes party occurrence in context of a marketing item instance (product, ser" +
				"vice, frame agreement, bundle,...). CDM entity name(s): PartyInMktItemInstanceIn" +
				"fo.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields" +
				"\":[{\"name\":\"customer\",\"type\":{\"type\":\"record\",\"name\":\"Customer\",\"doc\":\"Subject r" +
				"egistred in Customer Management. CDM entity name(s): Customer.\",\"namespace\":\"cz." +
				"kb.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"customerI" +
				"d\",\"doc\":\"Identifier of the customer  (KBID - identifier of customer in Customer" +
				" Management system). CDM attribute class name: CustomerCustomerId.\",\"type\":\"long" +
				"\"}]}},{\"name\":\"partyInMktItemInstanceRole\",\"type\":{\"type\":\"record\",\"name\":\"Party" +
				"InMktItemInstanceRole\",\"doc\":\"The role that a party has in a particular product " +
				"instance.It can be specific to each product, common across a group of products, " +
				"or even across all products.E.g. applicant, co-applicant, guarantor for consumer" +
				" loans#CZ#Role, kterou ma strana v konkretni instanci produktu.Muze byt specific" +
				"ka pro kazdy produkt, spolecna v ramci skupiny produktu nebo dokonce pro vsechny" +
				" produkty.Napr. zadatel, spoluzadatel, rucitel pro spotrebni uvery. CDM entity n" +
				"ame(s): PartyInMktItemInstanceRole.\",\"namespace\":\"cz.kb.api.mortgageservicingeve" +
				"nts.v3.mortgageinstance\",\"fields\":[{\"name\":\"partyInMktItemInstanceRoleCode\",\"typ" +
				"e\":{\"type\":\"record\",\"name\":\"PartyInMktItemInstanceRoleCode\",\"doc\":\"Multicodebook" +
				" property representing code of role (unique identifier) that parties in general " +
				"can have on products.It is multicodebook because roles always exists, but differ" +
				"s per product groups and are not managed centrally. CDM entity name(s): PartyInM" +
				"ktItemInstanceRoleCode.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortg" +
				"ageinstance\",\"fields\":[{\"name\":\"code\",\"doc\":\"Human readable unique identifier of" +
				" role on product instance. MultiCodebook value itself.Unique across all products" +
				". Attribute has specific codebook type: CB_CustomerInMortgageInstanceRole. CDM a" +
				"ttribute class name: PartyInMktItemInstanceRoleCodeCode. Attribute has simple ty" +
				"pe CB_MultiCodebookValue with description: Represents information that value can" +
				" be from more than one codebook. Codebook type: CB_CustomerInMortgageInstanceRol" +
				"e.\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"pattern\":\"^.{0,100}$\"}}" +
				"]}}]}}]}}},{\"name\":\"termination\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\"," +
				"\"name\":\"Termination\",\"doc\":\" CDM entity name(s): Termination.\",\"namespace\":\"cz.k" +
				"b.api.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"deactivate" +
				"dExactlyOn\",\"doc\":\"Date when product instance item was terminated or will be ter" +
				"minated (any way, e.g. canceled, loan repaid, account closed). CDM attribute cla" +
				"ss name: DeactivatedExactlyOn. Standard avro dateTime represented by the number " +
				"of milliseconds from the unix epoch, see avro specification: https://avro.apache" +
				".org/docs/1.8.0/spec.html. Consider using converters to dateTime class in code g" +
				"enerator (see KB Integration Platform wiki for schema registry chapter).\",\"type\"" +
				":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}]}]}},{\"name\":\"mortgageLoanK" +
				"ind\",\"doc\":\" CDM attribute class name: MortgageLoanKind. Codebook type: CB_Mortg" +
				"ageLoanKind.\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"nam" +
				"e\",\"doc\":\"Free text that contains name of product as <u>customer</u> or bank def" +
				"ines it for marketable item INSTANCE (version). Only relevant if different from " +
				"Catalogue names. CDM attribute class name: CommonInstanceItemName. Attribute has" +
				" simple type ST_String255 with description: General string of max length 255.\",\"" +
				"default\":null,\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\",\"patte" +
				"rn\":\"^.{0,255}$\"}]},{\"name\":\"PCP\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\"" +
				",\"name\":\"PCPInstanceId\",\"doc\":\"Multiattribute property of marketable item instan" +
				"ce.Multiattribute: Identifiers of marketable item instances are not yet unified," +
				" there is no one central catalogue.This also covers identifiers valid for only s" +
				"ome part of marketable item instance lifecycle, e.g. proposed product.E.g. PCP i" +
				"dentifiers, TSS identifiers.#CZ#Viceatributova promenna instanci prodejnych polo" +
				"zek. Viceatributovost: Identifikatory instanci prodejych polozek zatim nejsou sj" +
				"ednoceny. Neexistujce centralni katalog. Pokryva tez identifikatory, ktere jsou " +
				"platne pouze pro nektere casti zivotniho cyklu instanci prodejnych polozek (napr" +
				"iklad navrhovany produkt). Priklad: PCP identifikator, TSS identifikator. CDM en" +
				"tity name(s): InstanceId.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mor" +
				"tgageinstance\",\"fields\":[{\"name\":\"id\",\"doc\":\"Identifier of product instance item" +
				" itself.#CZ#Vlastni identifikator instance prodejne polozky. CDM attribute class" +
				" name: InstanceIdId. Attribute has simple type ST_IdStringDefault with descripti" +
				"on: Standard data type to be used ID, i.e. unique identifier. It is not supposed" +
				" to be human-readable.E.g.: AgreementID\",\"type\":{\"type\":\"string\",\"avro.java.stri" +
				"ng\":\"String\",\"pattern\":\"^.{0,30}$\"}}]}]},{\"name\":\"ProductDetailURIInNoby\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"URI\",\"doc\":\"Uniform Resource Id" +
				"entifierNapr./typicky http odkaz. CDM entity name(s): URI.\",\"namespace\":\"cz.kb.a" +
				"pi.mortgageservicingevents.v3.mortgageinstance\",\"fields\":[{\"name\":\"value\",\"doc\":" +
				"\"Complete URI. CDM attribute class name: URIValue. Attribute has simple type ST_" +
				"URI with description: A string representing a URI. Limited to 2047 characters.\"," +
				"\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"pattern\":\"^.{0,2048}$\"}}]}]" +
				"},{\"name\":\"Starbuild\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Sta" +
				"rbuildInstanceId\",\"doc\":\"Multiattribute property of marketable item instance.Mul" +
				"tiattribute: Identifiers of marketable item instances are not yet unified, there" +
				" is no one central catalogue.This also covers identifiers valid for only some pa" +
				"rt of marketable item instance lifecycle, e.g. proposed product.E.g. PCP identif" +
				"iers, TSS identifiers.#CZ#Viceatributova promenna instanci prodejnych polozek. V" +
				"iceatributovost: Identifikatory instanci prodejych polozek zatim nejsou sjednoce" +
				"ny. Neexistujce centralni katalog. Pokryva tez identifikatory, ktere jsou platne" +
				" pouze pro nektere casti zivotniho cyklu instanci prodejnych polozek (napriklad " +
				"navrhovany produkt). Priklad: PCP identifikator, TSS identifikator. CDM entity n" +
				"ame(s): InstanceId.\",\"namespace\":\"cz.kb.api.mortgageservicingevents.v3.mortgagei" +
				"nstance\",\"fields\":[{\"name\":\"id\",\"doc\":\"Identifier of product instance item itsel" +
				"f.#CZ#Vlastni identifikator instance prodejne polozky. CDM attribute class name:" +
				" InstanceIdId. Attribute has simple type ST_IdStringDefault with description: St" +
				"andard data type to be used ID, i.e. unique identifier. It is not supposed to be" +
				" human-readable.E.g.: AgreementID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"S" +
				"tring\",\"pattern\":\"^.{0,30}$\"}}]}]}]}},{\"name\":\"occurredOn\",\"doc\":\"Date and time " +
				"when event occurred. CDM attribute class name: EventOccurredOn. Standard avro da" +
				"teTime represented by the number of milliseconds from the unix epoch, see avro s" +
				"pecification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using conve" +
				"rters to dateTime class in code generator (see KB Integration Platform wiki for " +
				"schema registry chapter).\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis" +
				"\"}},{\"name\":\"Old\",\"default\":null,\"type\":[\"null\",\"cz.kb.api.mortgageservicingeven" +
				"ts.v3.mortgageinstance.MortgageInstance\"]}],\"javaAnnotation\":\"cz.kb.api.common.a" +
				"nnotation.ConfluentSchemaRegistryCompatible\"}");
		/// <summary>
		/// Unique identifier of event. CDM attribute class name: EventId. Attribute has simple type ST_String100 with description: General string of max length 100.
		/// </summary>
		private string _eventId;
		private cz.kb.api.mortgageservicingevents.v3.mortgageinstance.MortgageInstance _New;
		/// <summary>
		/// Date and time when event occurred. CDM attribute class name: EventOccurredOn. Standard avro dateTime represented by the number of milliseconds from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to dateTime class in code generator (see KB Integration Platform wiki for schema registry chapter).
		/// </summary>
		private System.DateTime _occurredOn;
		private cz.kb.api.mortgageservicingevents.v3.mortgageinstance.MortgageInstance _Old;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MortgageInstanceChanged._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of event. CDM attribute class name: EventId. Attribute has simple type ST_String100 with description: General string of max length 100.
		/// </summary>
		public string eventId
		{
			get
			{
				return this._eventId;
			}
			set
			{
				this._eventId = value;
			}
		}
		public cz.kb.api.mortgageservicingevents.v3.mortgageinstance.MortgageInstance New
		{
			get
			{
				return this._New;
			}
			set
			{
				this._New = value;
			}
		}
		/// <summary>
		/// Date and time when event occurred. CDM attribute class name: EventOccurredOn. Standard avro dateTime represented by the number of milliseconds from the unix epoch, see avro specification: https://avro.apache.org/docs/1.8.0/spec.html. Consider using converters to dateTime class in code generator (see KB Integration Platform wiki for schema registry chapter).
		/// </summary>
		public System.DateTime occurredOn
		{
			get
			{
				return this._occurredOn;
			}
			set
			{
				this._occurredOn = value;
			}
		}
		public cz.kb.api.mortgageservicingevents.v3.mortgageinstance.MortgageInstance Old
		{
			get
			{
				return this._Old;
			}
			set
			{
				this._Old = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.eventId;
			case 1: return this.New;
			case 2: return this.occurredOn;
			case 3: return this.Old;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.eventId = (System.String)fieldValue; break;
			case 1: this.New = (cz.kb.api.mortgageservicingevents.v3.mortgageinstance.MortgageInstance)fieldValue; break;
			case 2: this.occurredOn = (System.DateTime)fieldValue; break;
			case 3: this.Old = (cz.kb.api.mortgageservicingevents.v3.mortgageinstance.MortgageInstance)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
