DROP INDEX IF EXISTS [Idx_CaseId] ON [dbo].[ActiveTask];
GO
CREATE NONCLUSTERED INDEX [Idx_CaseId] ON [dbo].[ActiveTask]
(
	[CaseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

DROP INDEX IF EXISTS [Idx_OwnerUserId] ON [dbo].[Case];
GO
CREATE NONCLUSTERED INDEX [Idx_OwnerUserId] ON [dbo].[Case]
(
	[OwnerUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO