// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.kb.osbs.mcs.sender.sendapi.v2
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Verze dokumentuDocument can change over time. Document version captures document in a given time.Verze dokumentu (SLV 24-001, kapitola 01, bod 38 [1]) je nositelem vlastniho obsahu dokumentu. Kazdy dokument ma alespon jednu verzi. K jednomu dokumentu muze byt N verzi dokumentu. Verze jsou vyuziti pri postupnem vyvoji obsahu jednoho dokumentu (smlouva ve verzi 1, smlouva ve verzi 2 atp.)Reprezentuji postupny vyvoj dokumentu. Dalsi verze plne nahrazuje verzi predchozi, ktera se stava timto neplatnou.. ## Represents activity of content generation. Used to hold relationships to entities involved.. ## Represents any content.. ## Version information about content template. CDM entity name(s): DocumentVersion,ContentGeneration,Content,ContentTemplateVersion.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Binary : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Binary"",""doc"":""Verze dokumentuDocument can change over time. Document version captures document in a given time.Verze dokumentu (SLV 24-001, kapitola 01, bod 38 [1]) je nositelem vlastniho obsahu dokumentu. Kazdy dokument ma alespon jednu verzi. K jednomu dokumentu muze byt N verzi dokumentu. Verze jsou vyuziti pri postupnem vyvoji obsahu jednoho dokumentu (smlouva ve verzi 1, smlouva ve verzi 2 atp.)Reprezentuji postupny vyvoj dokumentu. Dalsi verze plne nahrazuje verzi predchozi, ktera se stava timto neplatnou.. ## Represents activity of content generation. Used to hold relationships to entities involved.. ## Represents any content.. ## Version information about content template. CDM entity name(s): DocumentVersion,ContentGeneration,Content,ContentTemplateVersion."",""namespace"":""cz.kb.osbs.mcs.sender.sendapi.v2"",""fields"":[{""name"":""binary"",""doc"":""Content in base64 binary format. CDM attribute class name: ContentBinary."",""type"":""bytes""},{""name"":""filename"",""doc"":""Name of the file in which the content is stored. As on filesystem. Full file name, suffix is included.E.g. consumerLoanContract2410.pdfNazev souboru s priponou windows complaint podobe: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions. CDM attribute class name: ContentFilename."",""type"":{""type"":""string"",""avro.java.string"":""String"",""pattern"":""^.{0,255}$""}}]}");
		/// <summary>
		/// Content in base64 binary format. CDM attribute class name: ContentBinary.
		/// </summary>
		private byte[] _binary;
		/// <summary>
		/// Name of the file in which the content is stored. As on filesystem. Full file name, suffix is included.E.g. consumerLoanContract2410.pdfNazev souboru s priponou windows complaint podobe: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions. CDM attribute class name: ContentFilename.
		/// </summary>
		private string _filename;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Binary._SCHEMA;
			}
		}
		/// <summary>
		/// Content in base64 binary format. CDM attribute class name: ContentBinary.
		/// </summary>
		public byte[] binary
		{
			get
			{
				return this._binary;
			}
			set
			{
				this._binary = value;
			}
		}
		/// <summary>
		/// Name of the file in which the content is stored. As on filesystem. Full file name, suffix is included.E.g. consumerLoanContract2410.pdfNazev souboru s priponou windows complaint podobe: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions. CDM attribute class name: ContentFilename.
		/// </summary>
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				this._filename = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.binary;
			case 1: return this.filename;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.binary = (System.Byte[])fieldValue; break;
			case 1: this.filename = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
