USE [master]
GO

/****** Object:  Database [CIS]    Script Date: 04.04.2022 19:29:39 ******/
CREATE DATABASE [CIS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CIS', FILENAME = N'F:\MSSQL15.SIT\MSSQL\DATA\CIS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CIS_log', FILENAME = N'G:\MSSQL15.SIT\MSSQL\Data\CIS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CIS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CIS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CIS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CIS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CIS] SET ARITHABORT OFF 
GO

ALTER DATABASE [CIS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CIS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CIS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CIS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CIS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CIS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CIS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CIS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CIS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CIS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CIS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CIS] SET RECOVERY FULL 
GO

ALTER DATABASE [CIS] SET  MULTI_USER 
GO

ALTER DATABASE [CIS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CIS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CIS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CIS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CIS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CIS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CIS] SET  READ_WRITE 
GO


