// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.mpss.api.starbuild.mortgage.workflow.inputprocessingevents.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// 
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class WorkflowInputProcessingContext : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""WorkflowInputProcessingContext"",""doc"":"""",""namespace"":""cz.mpss.api.starbuild.mortgage.workflow.inputprocessingevents.v1"",""fields"":[{""name"":""requestId"",""type"":""int""},{""name"":""requestProcessingResult"",""type"":{""type"":""enum"",""name"":""RequestProcessingResultEnum"",""doc"":"""",""namespace"":""cz.mpss.api.starbuild.mortgage.workflow.inputprocessingevents.v1"",""symbols"":[""CANCELED"",""ERROR"",""IGNORED"",""OK""]}}]}");
		private int _requestId;
		private cz.mpss.api.starbuild.mortgage.workflow.inputprocessingevents.v1.RequestProcessingResultEnum _requestProcessingResult;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return WorkflowInputProcessingContext._SCHEMA;
			}
		}
		public int requestId
		{
			get
			{
				return this._requestId;
			}
			set
			{
				this._requestId = value;
			}
		}
		public cz.mpss.api.starbuild.mortgage.workflow.inputprocessingevents.v1.RequestProcessingResultEnum requestProcessingResult
		{
			get
			{
				return this._requestProcessingResult;
			}
			set
			{
				this._requestProcessingResult = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.requestId;
			case 1: return this.requestProcessingResult;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.requestId = (System.Int32)fieldValue; break;
			case 1: this.requestProcessingResult = (cz.mpss.api.starbuild.mortgage.workflow.inputprocessingevents.v1.RequestProcessingResultEnum)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
