//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainServices.ProductService.ExternalServices.Pcp.V1.Client
{
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceSystemException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceSystemPermissionException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceSystemUnavailableException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceBusinessException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceValidationException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/ServiceException/v2")]
    public abstract partial class ServiceException
    {
        
        private string errorCodeField;
        
        private string messageField;
        
        private long uuidField;
        
        private string errorDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string errorDetail
        {
            get
            {
                return this.errorDetailField;
            }
            set
            {
                this.errorDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/ServiceException/v2")]
    public partial class ServiceValidationExceptionConstraint
    {
        
        private string messageField;
        
        private string pathField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class ReferentialMktItemInstanceId
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class ProductInstanceReference
    {
        
        private ReferentialMktItemInstanceId referentialMktItemInstanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReferentialMktItemInstanceId referentialMktItemInstanceId
        {
            get
            {
                return this.referentialMktItemInstanceIdField;
            }
            set
            {
                this.referentialMktItemInstanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class createResponse
    {
        
        private ProductInstanceReference productInstanceReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductInstanceReference productInstanceReference
        {
            get
            {
                return this.productInstanceReferenceField;
            }
            set
            {
                this.productInstanceReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class InfoSourceCode
    {
        
        private string classField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class InfoSource
    {
        
        private InfoSourceCode infoSourceCodeField;
        
        private System.DateTime onField;
        
        private bool onFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfoSourceCode infoSourceCode
        {
            get
            {
                return this.infoSourceCodeField;
            }
            set
            {
                this.infoSourceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime on
        {
            get
            {
                return this.onField;
            }
            set
            {
                this.onField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onSpecified
        {
            get
            {
                return this.onFieldSpecified;
            }
            set
            {
                this.onFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class ProductInstanceInfo
    {
        
        private Account accountField;
        
        private InfoSource infoSourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Account account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InfoSource infoSource
        {
            get
            {
                return this.infoSourceField;
            }
            set
            {
                this.infoSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class Account
    {
        
        private AccountNumber accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountNumber accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class AccountNumber
    {
        
        private string bankCodeField;
        
        private string coreField;
        
        private string prefixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bankCode
        {
            get
            {
                return this.bankCodeField;
            }
            set
            {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string core
        {
            get
            {
                return this.coreField;
            }
            set
            {
                this.coreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CatalogueItemId
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogueProductInOffer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO/create")]
    public partial class CommonCatalogueItem
    {
        
        private CatalogueItemId catalogueItemIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueItemId catalogueItemId
        {
            get
            {
                return this.catalogueItemIdField;
            }
            set
            {
                this.catalogueItemIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO/create")]
    public partial class CatalogueProductInOffer : CommonCatalogueItem
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO/create")]
    public partial class ProductInOffer
    {
        
        private CatalogueProductInOffer catalogueProductInOfferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueProductInOffer catalogueProductInOffer
        {
            get
            {
                return this.catalogueProductInOfferField;
            }
            set
            {
                this.catalogueProductInOfferField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MktItemInstanceIdByAccount))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class OtherMktItemInstanceId
    {
        
        private string classField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class MktItemInstanceIdByAccount : OtherMktItemInstanceId
    {
        
        private Account accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Account account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class MktItemInstanceState
    {
        
        private string classField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class MktItemInstanceId
    {
        
        private string classField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class RelatedProductInstanceReference
    {
        
        private MktItemInstanceId mktItemInstanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MktItemInstanceId mktItemInstanceId
        {
            get
            {
                return this.mktItemInstanceIdField;
            }
            set
            {
                this.mktItemInstanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class MktItemInstanceRelationship
    {
        
        private RelatedProductInstanceReference relatedProductInstanceReferenceField;
        
        private string purposeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RelatedProductInstanceReference relatedProductInstanceReference
        {
            get
            {
                return this.relatedProductInstanceReferenceField;
            }
            set
            {
                this.relatedProductInstanceReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class PartyInproductInstanceRoleCode
    {
        
        private string classField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class PartyInProductInstanceRole
    {
        
        private PartyInproductInstanceRoleCode partyInproductInstanceRoleCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PartyInproductInstanceRoleCode partyInproductInstanceRoleCode
        {
            get
            {
                return this.partyInproductInstanceRoleCodeField;
            }
            set
            {
                this.partyInproductInstanceRoleCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class KBCustomer
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CustomerInProductInstance
    {
        
        private KBCustomer kBCustomerField;
        
        private PartyInProductInstanceRole partyInProductInstanceRoleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KBCustomer kBCustomer
        {
            get
            {
                return this.kBCustomerField;
            }
            set
            {
                this.kBCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartyInProductInstanceRole partyInProductInstanceRole
        {
            get
            {
                return this.partyInProductInstanceRoleField;
            }
            set
            {
                this.partyInProductInstanceRoleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO/create")]
    public partial class ProductInstance
    {
        
        private CustomerInProductInstance[] customerInProductInstanceListField;
        
        private MktItemInstanceRelationship[] mktItemInstanceRelationshipListField;
        
        private MktItemInstanceState mktItemInstanceStateField;
        
        private OtherMktItemInstanceId[] otherMktItemInstanceIdListField;
        
        private ProductInOffer productInOfferField;
        
        private ProductInstanceInfo productInstanceInfoField;
        
        private System.DateTime createdOnField;
        
        private bool createdOnFieldSpecified;
        
        private string nameField;
        
        private System.DateTime soldOnField;
        
        private bool soldOnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customerInProductInstance", IsNullable=false)]
        public CustomerInProductInstance[] customerInProductInstanceList
        {
            get
            {
                return this.customerInProductInstanceListField;
            }
            set
            {
                this.customerInProductInstanceListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mktItemInstanceRelationship", IsNullable=false)]
        public MktItemInstanceRelationship[] mktItemInstanceRelationshipList
        {
            get
            {
                return this.mktItemInstanceRelationshipListField;
            }
            set
            {
                this.mktItemInstanceRelationshipListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MktItemInstanceState mktItemInstanceState
        {
            get
            {
                return this.mktItemInstanceStateField;
            }
            set
            {
                this.mktItemInstanceStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("otherMktItemInstanceId", IsNullable=false)]
        public OtherMktItemInstanceId[] otherMktItemInstanceIdList
        {
            get
            {
                return this.otherMktItemInstanceIdListField;
            }
            set
            {
                this.otherMktItemInstanceIdListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ProductInOffer productInOffer
        {
            get
            {
                return this.productInOfferField;
            }
            set
            {
                this.productInOfferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ProductInstanceInfo productInstanceInfo
        {
            get
            {
                return this.productInstanceInfoField;
            }
            set
            {
                this.productInstanceInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime createdOn
        {
            get
            {
                return this.createdOnField;
            }
            set
            {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdOnSpecified
        {
            get
            {
                return this.createdOnFieldSpecified;
            }
            set
            {
                this.createdOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime soldOn
        {
            get
            {
                return this.soldOnField;
            }
            set
            {
                this.soldOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool soldOnSpecified
        {
            get
            {
                return this.soldOnFieldSpecified;
            }
            set
            {
                this.soldOnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class createRequest
    {
        
        private ProductInstance productInstanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductInstance productInstance
        {
            get
            {
                return this.productInstanceField;
            }
            set
            {
                this.productInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceSystemPermissionException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceSystemUnavailableException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/ServiceException/v2")]
    public partial class ServiceSystemException : ServiceException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/ServiceException/v2")]
    public partial class ServiceSystemPermissionException : ServiceSystemException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/ServiceException/v2")]
    public partial class ServiceSystemUnavailableException : ServiceSystemException
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceValidationException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/ServiceException/v2")]
    public partial class ServiceBusinessException : ServiceException
    {
        
        private string originalErrorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string originalErrorCode
        {
            get
            {
                return this.originalErrorCodeField;
            }
            set
            {
                this.originalErrorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/ServiceException/v2")]
    public partial class ServiceValidationException : ServiceBusinessException
    {
        
        private ServiceValidationExceptionConstraint[] serviceValidationExceptionConstraintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceValidationExceptionConstraint", Order=0)]
        public ServiceValidationExceptionConstraint[] serviceValidationExceptionConstraint
        {
            get
            {
                return this.serviceValidationExceptionConstraintField;
            }
            set
            {
                this.serviceValidationExceptionConstraintField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", ConfigurationName="DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBESer" +
        "vice")]
    internal interface ProductInstanceBEService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ServiceException), Action="", Name="serviceException", Namespace="http://kb.cz/DataModel/Technical/Exceptions/v2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonCatalogueItem))]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createResponse1> createAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ServiceException), Action="", Name="serviceException", Namespace="http://kb.cz/DataModel/Technical/Exceptions/v2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonCatalogueItem))]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteResponse1> deleteAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ServiceException), Action="", Name="serviceException", Namespace="http://kb.cz/DataModel/Technical/Exceptions/v2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonCatalogueItem))]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdResponse1> getByCustomerIdAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ServiceException), Action="", Name="serviceException", Namespace="http://kb.cz/DataModel/Technical/Exceptions/v2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonCatalogueItem))]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsResponse1> getByIdsAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ServiceException), Action="", Name="serviceException", Namespace="http://kb.cz/DataModel/Technical/Exceptions/v2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonCatalogueItem))]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsResponse1> getByOtherIdsAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ServiceException), Action="", Name="serviceException", Namespace="http://kb.cz/DataModel/Technical/Exceptions/v2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonCatalogueItem))]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateResponse1> updateAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/HeaderTypes/v1")]
    public partial class SystemIdentity
    {
        
        private Application originatorField;
        
        private Application callerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Application originator
        {
            get
            {
                return this.originatorField;
            }
            set
            {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Application caller
        {
            get
            {
                return this.callerField;
            }
            set
            {
                this.callerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/HeaderTypes/v1")]
    public partial class Application
    {
        
        private string applicationField;
        
        private string applicationComponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string applicationComponent
        {
            get
            {
                return this.applicationComponentField;
            }
            set
            {
                this.applicationComponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/DataModel/Technical/HeaderTypes/v1")]
    public partial class TraceContext
    {
        
        private string traceIdField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string traceId
        {
            get
            {
                return this.traceIdField;
            }
            set
            {
                this.traceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class createRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createRequest createRequest;
        
        public createRequest1()
        {
        }
        
        public createRequest1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createRequest createRequest)
        {
            this.systemIdentity = systemIdentity;
            this.traceContext = traceContext;
            this.createRequest = createRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class createResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createResponse createResponse;
        
        public createResponse1()
        {
        }
        
        public createResponse1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createResponse createResponse)
        {
            this.createResponse = createResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class deleteRequest
    {
        
        private ProductInstanceReference productInstanceReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductInstanceReference productInstanceReference
        {
            get
            {
                return this.productInstanceReferenceField;
            }
            set
            {
                this.productInstanceReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class deleteResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class deleteRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteRequest deleteRequest;
        
        public deleteRequest1()
        {
        }
        
        public deleteRequest1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteRequest deleteRequest)
        {
            this.systemIdentity = systemIdentity;
            this.traceContext = traceContext;
            this.deleteRequest = deleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class deleteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteResponse deleteResponse;
        
        public deleteResponse1()
        {
        }
        
        public deleteResponse1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteResponse deleteResponse)
        {
            this.deleteResponse = deleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class getByCustomerIdRequest
    {
        
        private KBCustomer kBCustomerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KBCustomer kBCustomer
        {
            get
            {
                return this.kBCustomerField;
            }
            set
            {
                this.kBCustomerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class getByCustomerIdResponse
    {
        
        private ProductInstance2[] productInstanceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("productInstance", IsNullable=false)]
        public ProductInstance2[] productInstanceList
        {
            get
            {
                return this.productInstanceListField;
            }
            set
            {
                this.productInstanceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ProductInstance", Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO/getByCustomerId")]
    public partial class ProductInstance2
    {
        
        private CatalogueProductInOfferSpecs catalogueProductInOfferSpecsField;
        
        private CustomerInProductInstance[] customerInProductInstanceListField;
        
        private MktItemInstanceState mktItemInstanceStateField;
        
        private OtherMktItemInstanceId[] otherMktItemInstanceIdListField;
        
        private ReferentialMktItemInstanceId referentialMktItemInstanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueProductInOfferSpecs catalogueProductInOfferSpecs
        {
            get
            {
                return this.catalogueProductInOfferSpecsField;
            }
            set
            {
                this.catalogueProductInOfferSpecsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customerInProductInstance", IsNullable=false)]
        public CustomerInProductInstance[] customerInProductInstanceList
        {
            get
            {
                return this.customerInProductInstanceListField;
            }
            set
            {
                this.customerInProductInstanceListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MktItemInstanceState mktItemInstanceState
        {
            get
            {
                return this.mktItemInstanceStateField;
            }
            set
            {
                this.mktItemInstanceStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("otherMktItemInstanceId", IsNullable=false)]
        public OtherMktItemInstanceId[] otherMktItemInstanceIdList
        {
            get
            {
                return this.otherMktItemInstanceIdListField;
            }
            set
            {
                this.otherMktItemInstanceIdListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ReferentialMktItemInstanceId referentialMktItemInstanceId
        {
            get
            {
                return this.referentialMktItemInstanceIdField;
            }
            set
            {
                this.referentialMktItemInstanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CatalogueProductInOfferSpecs : CommonCatalogueProductInOffer
    {
        
        private CatalogueBusinessProductSpecs catalogueBusinessProductSpecsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueBusinessProductSpecs catalogueBusinessProductSpecs
        {
            get
            {
                return this.catalogueBusinessProductSpecsField;
            }
            set
            {
                this.catalogueBusinessProductSpecsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CatalogueBusinessProductSpecs : CommonCatalogueBusinessProduct
    {
        
        private CatalogueTechnicalProductSpecs catalogueTechnicalProductSpecsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueTechnicalProductSpecs catalogueTechnicalProductSpecs
        {
            get
            {
                return this.catalogueTechnicalProductSpecsField;
            }
            set
            {
                this.catalogueTechnicalProductSpecsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CatalogueTechnicalProductSpecs : CommonCatalogueTechnicalItem
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogueTechnicalProductSpecs))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CommonCatalogueTechnicalItem
    {
        
        private CatalogueItemObjectCode catalogueItemObjectCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueItemObjectCode catalogueItemObjectCode
        {
            get
            {
                return this.catalogueItemObjectCodeField;
            }
            set
            {
                this.catalogueItemObjectCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CatalogueItemObjectCode
    {
        
        private string objectCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string objectCode
        {
            get
            {
                return this.objectCodeField;
            }
            set
            {
                this.objectCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogueBusinessProductSpecs))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CommonCatalogueBusinessProduct
    {
        
        private CatalogueItemId catalogueItemIdField;
        
        private CatalogueItemObjectCode catalogueItemObjectCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueItemId catalogueItemId
        {
            get
            {
                return this.catalogueItemIdField;
            }
            set
            {
                this.catalogueItemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CatalogueItemObjectCode catalogueItemObjectCode
        {
            get
            {
                return this.catalogueItemObjectCodeField;
            }
            set
            {
                this.catalogueItemObjectCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogueProductInOfferSpecs))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class CommonCatalogueProductInOffer
    {
        
        private CatalogueItemId catalogueItemIdField;
        
        private CatalogueItemObjectCode catalogueItemObjectCodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueItemId catalogueItemId
        {
            get
            {
                return this.catalogueItemIdField;
            }
            set
            {
                this.catalogueItemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CatalogueItemObjectCode catalogueItemObjectCode
        {
            get
            {
                return this.catalogueItemObjectCodeField;
            }
            set
            {
                this.catalogueItemObjectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getByCustomerIdRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdRequest getByCustomerIdRequest;
        
        public getByCustomerIdRequest1()
        {
        }
        
        public getByCustomerIdRequest1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdRequest getByCustomerIdRequest)
        {
            this.systemIdentity = systemIdentity;
            this.traceContext = traceContext;
            this.getByCustomerIdRequest = getByCustomerIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getByCustomerIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdResponse getByCustomerIdResponse;
        
        public getByCustomerIdResponse1()
        {
        }
        
        public getByCustomerIdResponse1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdResponse getByCustomerIdResponse)
        {
            this.getByCustomerIdResponse = getByCustomerIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class getByIdsRequest
    {
        
        private ProductInstanceReference[] productInstanceReferenceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("productInstanceReference", IsNullable=false)]
        public ProductInstanceReference[] productInstanceReferenceList
        {
            get
            {
                return this.productInstanceReferenceListField;
            }
            set
            {
                this.productInstanceReferenceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class getByIdsResponse
    {
        
        private ProductInstance3[] productInstanceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("productInstance", IsNullable=false)]
        public ProductInstance3[] productInstanceList
        {
            get
            {
                return this.productInstanceListField;
            }
            set
            {
                this.productInstanceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ProductInstance", Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class ProductInstance3
    {
        
        private CatalogueProductInOfferSpecs catalogueProductInOfferSpecsField;
        
        private CustomerInProductInstance[] customerInProductInstanceListField;
        
        private MktItemInstanceRelationship[] mktItemInstanceRelationshipListField;
        
        private MktItemInstanceState mktItemInstanceStateField;
        
        private OtherMktItemInstanceId[] otherMktItemInstanceIdListField;
        
        private ProductInstanceArchFlag productInstanceArchFlagField;
        
        private ProductInstanceInfo productInstanceInfoField;
        
        private ReferentialMktItemInstanceId referentialMktItemInstanceIdField;
        
        private System.DateTime createdOnField;
        
        private bool createdOnFieldSpecified;
        
        private System.DateTime lastModifiedOnField;
        
        private string nameField;
        
        private System.DateTime soldOnField;
        
        private bool soldOnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CatalogueProductInOfferSpecs catalogueProductInOfferSpecs
        {
            get
            {
                return this.catalogueProductInOfferSpecsField;
            }
            set
            {
                this.catalogueProductInOfferSpecsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customerInProductInstance", IsNullable=false)]
        public CustomerInProductInstance[] customerInProductInstanceList
        {
            get
            {
                return this.customerInProductInstanceListField;
            }
            set
            {
                this.customerInProductInstanceListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mktItemInstanceRelationship", IsNullable=false)]
        public MktItemInstanceRelationship[] mktItemInstanceRelationshipList
        {
            get
            {
                return this.mktItemInstanceRelationshipListField;
            }
            set
            {
                this.mktItemInstanceRelationshipListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MktItemInstanceState mktItemInstanceState
        {
            get
            {
                return this.mktItemInstanceStateField;
            }
            set
            {
                this.mktItemInstanceStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("otherMktItemInstanceId", IsNullable=false)]
        public OtherMktItemInstanceId[] otherMktItemInstanceIdList
        {
            get
            {
                return this.otherMktItemInstanceIdListField;
            }
            set
            {
                this.otherMktItemInstanceIdListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ProductInstanceArchFlag productInstanceArchFlag
        {
            get
            {
                return this.productInstanceArchFlagField;
            }
            set
            {
                this.productInstanceArchFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ProductInstanceInfo productInstanceInfo
        {
            get
            {
                return this.productInstanceInfoField;
            }
            set
            {
                this.productInstanceInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ReferentialMktItemInstanceId referentialMktItemInstanceId
        {
            get
            {
                return this.referentialMktItemInstanceIdField;
            }
            set
            {
                this.referentialMktItemInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime createdOn
        {
            get
            {
                return this.createdOnField;
            }
            set
            {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdOnSpecified
        {
            get
            {
                return this.createdOnFieldSpecified;
            }
            set
            {
                this.createdOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime lastModifiedOn
        {
            get
            {
                return this.lastModifiedOnField;
            }
            set
            {
                this.lastModifiedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime soldOn
        {
            get
            {
                return this.soldOnField;
            }
            set
            {
                this.soldOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool soldOnSpecified
        {
            get
            {
                return this.soldOnFieldSpecified;
            }
            set
            {
                this.soldOnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class ProductInstanceArchFlag
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getByIdsRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsRequest getByIdsRequest;
        
        public getByIdsRequest1()
        {
        }
        
        public getByIdsRequest1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsRequest getByIdsRequest)
        {
            this.systemIdentity = systemIdentity;
            this.traceContext = traceContext;
            this.getByIdsRequest = getByIdsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getByIdsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsResponse getByIdsResponse;
        
        public getByIdsResponse1()
        {
        }
        
        public getByIdsResponse1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsResponse getByIdsResponse)
        {
            this.getByIdsResponse = getByIdsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class getByOtherIdsRequest
    {
        
        private ProductInstanceReference1[] productInstanceReferenceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("productInstanceReference", IsNullable=false)]
        public ProductInstanceReference1[] productInstanceReferenceList
        {
            get
            {
                return this.productInstanceReferenceListField;
            }
            set
            {
                this.productInstanceReferenceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ProductInstanceReference", Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO/getByOtherId")]
    public partial class ProductInstanceReference1
    {
        
        private OtherMktItemInstanceId otherMktItemInstanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OtherMktItemInstanceId otherMktItemInstanceId
        {
            get
            {
                return this.otherMktItemInstanceIdField;
            }
            set
            {
                this.otherMktItemInstanceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class getByOtherIdsResponse
    {
        
        private ProductInstance3[] productInstanceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("productInstance", IsNullable=false)]
        public ProductInstance3[] productInstanceList
        {
            get
            {
                return this.productInstanceListField;
            }
            set
            {
                this.productInstanceListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getByOtherIdsRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsRequest getByOtherIdsRequest;
        
        public getByOtherIdsRequest1()
        {
        }
        
        public getByOtherIdsRequest1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsRequest getByOtherIdsRequest)
        {
            this.systemIdentity = systemIdentity;
            this.traceContext = traceContext;
            this.getByOtherIdsRequest = getByOtherIdsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getByOtherIdsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsResponse getByOtherIdsResponse;
        
        public getByOtherIdsResponse1()
        {
        }
        
        public getByOtherIdsResponse1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsResponse getByOtherIdsResponse)
        {
            this.getByOtherIdsResponse = getByOtherIdsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class updateRequest
    {
        
        private ProductInstance3 productInstanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductInstance3 productInstance
        {
            get
            {
                return this.productInstanceField;
            }
            set
            {
                this.productInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1/DTO")]
    public partial class updateResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class updateRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kb.cz/DataModel/Technical/Headers/v1")]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateRequest updateRequest;
        
        public updateRequest1()
        {
        }
        
        public updateRequest1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateRequest updateRequest)
        {
            this.systemIdentity = systemIdentity;
            this.traceContext = traceContext;
            this.updateRequest = updateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class updateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kb.cz/ProductInstanceBEService/v1", Order=0)]
        public DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateResponse updateResponse;
        
        public updateResponse1()
        {
        }
        
        public updateResponse1(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateResponse updateResponse)
        {
            this.updateResponse = updateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface ProductInstanceBEServiceChannel : DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class ProductInstanceBEServiceClient : System.ServiceModel.ClientBase<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService>, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductInstanceBEServiceClient() : 
                base(ProductInstanceBEServiceClient.GetDefaultBinding(), ProductInstanceBEServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProductInstanceBEServiceServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductInstanceBEServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductInstanceBEServiceClient.GetBindingForEndpoint(endpointConfiguration), ProductInstanceBEServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductInstanceBEServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductInstanceBEServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductInstanceBEServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductInstanceBEServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductInstanceBEServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createResponse1> DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService.createAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createRequest1 request)
        {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createResponse1> createAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createRequest createRequest)
        {
            DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createRequest1 inValue = new DomainServices.ProductService.ExternalServices.Pcp.V1.Client.createRequest1();
            inValue.systemIdentity = systemIdentity;
            inValue.traceContext = traceContext;
            inValue.createRequest = createRequest;
            return ((DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteResponse1> DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService.deleteAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteRequest1 request)
        {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteResponse1> deleteAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteRequest deleteRequest)
        {
            DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteRequest1 inValue = new DomainServices.ProductService.ExternalServices.Pcp.V1.Client.deleteRequest1();
            inValue.systemIdentity = systemIdentity;
            inValue.traceContext = traceContext;
            inValue.deleteRequest = deleteRequest;
            return ((DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdResponse1> DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService.getByCustomerIdAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdRequest1 request)
        {
            return base.Channel.getByCustomerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdResponse1> getByCustomerIdAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdRequest getByCustomerIdRequest)
        {
            DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdRequest1 inValue = new DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByCustomerIdRequest1();
            inValue.systemIdentity = systemIdentity;
            inValue.traceContext = traceContext;
            inValue.getByCustomerIdRequest = getByCustomerIdRequest;
            return ((DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService)(this)).getByCustomerIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsResponse1> DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService.getByIdsAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsRequest1 request)
        {
            return base.Channel.getByIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsResponse1> getByIdsAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsRequest getByIdsRequest)
        {
            DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsRequest1 inValue = new DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByIdsRequest1();
            inValue.systemIdentity = systemIdentity;
            inValue.traceContext = traceContext;
            inValue.getByIdsRequest = getByIdsRequest;
            return ((DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService)(this)).getByIdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsResponse1> DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService.getByOtherIdsAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsRequest1 request)
        {
            return base.Channel.getByOtherIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsResponse1> getByOtherIdsAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsRequest getByOtherIdsRequest)
        {
            DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsRequest1 inValue = new DomainServices.ProductService.ExternalServices.Pcp.V1.Client.getByOtherIdsRequest1();
            inValue.systemIdentity = systemIdentity;
            inValue.traceContext = traceContext;
            inValue.getByOtherIdsRequest = getByOtherIdsRequest;
            return ((DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService)(this)).getByOtherIdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateResponse1> DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService.updateAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateRequest1 request)
        {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateResponse1> updateAsync(DomainServices.ProductService.ExternalServices.Pcp.V1.Client.SystemIdentity systemIdentity, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.TraceContext traceContext, DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateRequest updateRequest)
        {
            DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateRequest1 inValue = new DomainServices.ProductService.ExternalServices.Pcp.V1.Client.updateRequest1();
            inValue.systemIdentity = systemIdentity;
            inValue.traceContext = traceContext;
            inValue.updateRequest = updateRequest;
            return ((DomainServices.ProductService.ExternalServices.Pcp.V1.Client.ProductInstanceBEService)(this)).updateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductInstanceBEServiceServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductInstanceBEServiceServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/services/ProductInstanceBEService/v1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProductInstanceBEServiceClient.GetBindingForEndpoint(EndpointConfiguration.ProductInstanceBEServiceServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProductInstanceBEServiceClient.GetEndpointAddress(EndpointConfiguration.ProductInstanceBEServiceServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ProductInstanceBEServiceServicePort,
        }
    }
}
