//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Collections.Generic;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable CS8765 // Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes).

namespace NOBY.ApiContracts
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressAddressSearchRequest
    {
        /// <summary>
        /// SessionId generované přímo na frontendu (unikátní GUID)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("sessionId")]
        [System.ComponentModel.DataAnnotations.Required]
        public string SessionId { get; set; } = default!;

        /// <summary>
        /// Pattern, podle kterého vyhledáváme
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("searchText")]
        [System.ComponentModel.DataAnnotations.Required]
        public string SearchText { get; set; } = default!;

        /// <summary>
        /// Id státu z číselníku Country
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("countryId")]
        public int? CountryId { get; set; } = default!;

        /// <summary>
        /// Počet vrácených záznamů
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressAddressSearchResponse
    {
        /// <summary>
        /// Počet vrácených záznamů
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("rows")]
        public List<AddressAddressSearchAddressLine>? Rows { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressAddressSearchAddressLine
    {
        /// <summary>
        /// Textová reprezentace adresy
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        public string Title { get; set; } = default!;

        /// <summary>
        /// Id adresy
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressGetAddressDetailRequest
    {
        /// <summary>
        /// SessionId generované přímo na frontendu (unikátní GUID)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("sessionId")]
        [System.ComponentModel.DataAnnotations.Required]
        public string SessionId { get; set; } = default!;

        /// <summary>
        /// Id adresy
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("addressId")]
        [System.ComponentModel.DataAnnotations.Required]
        public string AddressId { get; set; } = default!;

        /// <summary>
        /// Parametr title našeptávače adres
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Title { get; set; } = default!;

        /// <summary>
        /// Id státu z číselníku Country
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("countryId")]
        public int CountryId { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressGetAddressDetailResponse
    {
        /// <summary>
        /// Dodatek ulice, např. Recepce 2. patro
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("deliveryDetails")]
        public string? DeliveryDetails { get; set; } = default!;

        /// <summary>
        /// Ulice - AddressWhispererBEService|street
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("street")]
        public string? Street { get; set; } = default!;

        /// <summary>
        /// Číslo orientační - pro CZ/SK adresy mapujeme z AddressWhispererBEService|streetNumber, pro ostatní státy nemapujeme
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("streetNumber")]
        public string? StreetNumber { get; set; } = default!;

        /// <summary>
        /// Číslo popisné - pro CZ/SK adresy mapujeme z AddressWhispererBEService|landRegisterNumber, pro ostatní z AddressWhispererBEService|landRegisterNumber a pokud je prázdné, tak z AddressWhispererBEService|streetNumber
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("houseNumber")]
        public string? HouseNumber { get; set; } = default!;

        /// <summary>
        /// Číslo evidenční - pro CZ/SK adresy mapujeme z AddressWhispererBEService|evidenceNumber, pro ostatní státy nemapujeme
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("evidenceNumber")]
        public string? EvidenceNumber { get; set; } = default!;

        /// <summary>
        /// PSČ - AddressWhispererBEService|postCode
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("postcode")]
        public string? Postcode { get; set; } = default!;

        /// <summary>
        /// Město - AddressWhispererBEService|city. Pokud regEx 'Praha ([1-2][0-9]|[1-9])' tak hodnota 'Praha'
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("city")]
        public string? City { get; set; } = default!;

        /// <summary>
        /// Název části obce - AddressWhispererBEService|cityDistrict
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("cityDistrict")]
        public string? CityDistrict { get; set; } = default!;

        /// <summary>
        /// Obvod Prahy - AddressWhispererBEService|city pokud regEx 'Praha ([1-2][0-9]|[1-9])', jinak null
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pragueDistrict")]
        public string? PragueDistrict { get; set; } = default!;

        /// <summary>
        /// Id RUIAN adresního bodu - AddressWhispererBEService|id
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("addressPointId")]
        public string? AddressPointId { get; set; } = default!;

        /// <summary>
        /// KATUZ ID, pětimístné číslo katastrálního území, Id RUIAN katastrálního území - AddressWhispererBEService|cadastralAreaId
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("katuzId")]
        public int? KatuzId { get; set; } = default!;

        /// <summary>
        /// KATUZ, název katastrálního území, RUIAN katastrální území - AddressWhispererBEService|cadastralArea
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("katuzTitle")]
        public string? KatuzTitle { get; set; } = default!;

        /// <summary>
        /// Stát - AddressWhispererBEService|country
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("countryId")]
        public int? CountryId { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressKatuzSearchKatuzLine
    {
        /// <summary>
        /// Id katastrálního území (KATUZ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("katuzId")]
        public int KatuzId { get; set; } = default!;

        /// <summary>
        /// Textová reprezentace katastrálního území
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("katuzTitle")]
        public string KatuzTitle { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressKatuzSearchRequest
    {
        /// <summary>
        /// Pattern, podle kterého vyhledáváme
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("searchText")]
        [System.ComponentModel.DataAnnotations.Required]
        public string SearchText { get; set; } = default!;

        /// <summary>
        /// Počet vrácených záznamů
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressKatuzSearchResponse
    {
        /// <summary>
        /// Počet vrácených záznamů
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("rows")]
        public List<AddressKatuzSearchKatuzLine>? Rows { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesCancelCaseResponse
    {
        /// <summary>
        /// Stavy Case
        /// <br/>
        /// <br/>&lt;small&gt;Enum Values&lt;/small&gt;&lt;ul&gt;&lt;li&gt;1 - InProgress&lt;/li&gt;&lt;li&gt;2 - InApproval&lt;/li&gt;&lt;li&gt;3 - InSigning&lt;/li&gt;&lt;li&gt;4 - InDisbursement&lt;/li&gt;&lt;li&gt;5 - InAdministration&lt;/li&gt;&lt;li&gt;6 - Finished&lt;/li&gt;&lt;li&gt;7 - Cancelled&lt;/li&gt;&lt;li&gt;8 - InApprovalConfirmed&lt;/li&gt;&lt;li&gt;9 - ToBeCancelled&lt;/li&gt;&lt;li&gt;10 - ToBeCancelledConfirmed&lt;/li&gt;&lt;/ul&gt;
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        public CasesCancelCaseResponseState State { get; set; } = default!;

        /// <summary>
        /// Slovne nazev stavu Case
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("stateName")]
        public string? StateName { get; set; } = default!;

        /// <summary>
        /// Účely úvěru
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("customersOnSa")]
        public List<CasesCancelCaseCustomerOnSAItem>? CustomersOnSa { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesCancelCaseCustomerOnSAItem
    {
        /// <summary>
        /// Id customera na sales arrangementu
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("customerOnSAId")]
        public int CustomerOnSAId { get; set; } = default!;

        /// <summary>
        /// Jméno
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("firstName")]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 1)]
        public string FirstName { get; set; } = default!;

        /// <summary>
        /// Příjmení
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("lastName")]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 1)]
        public string LastName { get; set; } = default!;

        /// <summary>
        /// Datum narození
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("birthDate")]
        public System.DateTime BirthDate { get; set; } = default!;

        /// <summary>
        /// eArchiv ID dokumentu s potvrzení pro daného klienta
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("documentId")]
        public string DocumentId { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesSearchCasesRequest
    {
        /// <summary>
        /// [optional] ID pozadovaneho stavu filtru.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("filterId")]
        public int? FilterId { get; set; } = default!;

        /// <summary>
        /// [optional] Klicove slovo pro vyhledavani nad Cases.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("term")]
        public string? Term { get; set; } = default!;

        /// <summary>
        /// Nastaveni strankovani a razeni kolekce Cases.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pagination")]
        public SharedTypesPaginationRequest? Pagination { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesSearchCasesResponse
    {
        /// <summary>
        /// Informace o strankovani a razeni.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pagination")]
        public SharedTypesPaginationResponse? Pagination { get; set; } = default!;

        /// <summary>
        /// Kolekce nalezenych Case-s.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rows")]
        public List<CasesSharedCaseModel>? Rows { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesGetCaseMenuFlagsResponse
    {
        /// <summary>
        /// Položka menu Dokumenty
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("documentsMenuItem")]
        public CasesGetCaseMenuFlagsItem DocumentsMenuItem { get; set; } = default!;

        /// <summary>
        /// Položka menu Podmínky ke splnění
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("covenantsMenuItem")]
        public CasesGetCaseMenuFlagsItem CovenantsMenuItem { get; set; } = default!;

        /// <summary>
        /// Položka menu Nemovitosti
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("realEstatesMenuItem")]
        public CasesGetCaseMenuFlagsItem RealEstatesMenuItem { get; set; } = default!;

        /// <summary>
        /// Položka menu Parametry
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("parametersMenuItem")]
        public CasesGetCaseMenuFlagsItem ParametersMenuItem { get; set; } = default!;

        /// <summary>
        /// Položka menu Žadatelé
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("debtorsItem")]
        public CasesGetCaseMenuFlagsItem DebtorsItem { get; set; } = default!;

        /// <summary>
        /// Položka menu Požadavky a změny
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("changeRequestsMenuItem")]
        public CasesGetCaseMenuFlagsItem ChangeRequestsMenuItem { get; set; } = default!;

        /// <summary>
        /// Položka menu Úkoly
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("tasksMenuItem")]
        public CasesGetCaseMenuFlagsItem TasksMenuItem { get; set; } = default!;

        /// <summary>
        /// Změna úrokové sazby
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("refinancingMenuItem")]
        public CasesGetCaseMenuFlagsItem RefinancingMenuItem { get; set; } = default!;

        /// <summary>
        /// Mimořádná splátka
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("extraPaymentMenuItem")]
        public CasesGetCaseMenuFlagsItem ExtraPaymentMenuItem { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesGetCaseMenuFlagsItem
    {
        /// <summary>
        /// Příznak
        /// <br/>
        /// <br/>&lt;small&gt;Enum Values&lt;/small&gt;&lt;ul&gt;&lt;li&gt;0 - NoFlag&lt;/li&gt;&lt;li&gt;1 - InProcessing&lt;/li&gt;&lt;li&gt;2 - ExclamationMark&lt;/li&gt;&lt;/ul&gt;
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("flag")]
        public CasesGetCaseMenuFlagsItemFlag Flag { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isActive")]
        public bool IsActive { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesSharedCaseModel
    {

        [System.Text.Json.Serialization.JsonPropertyName("caseOwner")]
        public CasesSharedCaseOwnerModel? CaseOwner { get; set; } = default!;

        /// <summary>
        /// Unikátní Id obchodního případu
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("caseId")]
        public long CaseId { get; set; } = default!;

        /// <summary>
        /// Identita klienta
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("customerIdentity")]
        public SharedTypesCustomerIdentity? CustomerIdentity { get; set; } = default!;

        /// <summary>
        /// FO/FOP/Cizinec/Nezletilec: Jméno
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("firstName")]
        public string? FirstName { get; set; } = default!;

        /// <summary>
        /// FO/FOP/Cizinec/Nezletilec: Příjmení
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("lastName")]
        public string? LastName { get; set; } = default!;

        /// <summary>
        /// FO/FOP/Cizinec/Nezletilec: Datum narození klienta
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateOfBirth")]
        public DateOnly? DateOfBirth { get; set; } = default!;

        /// <summary>
        /// Stavy Case
        /// <br/>
        /// <br/>&lt;small&gt;Enum Values&lt;/small&gt;&lt;ul&gt;&lt;li&gt;1 - InProgress&lt;/li&gt;&lt;li&gt;2 - InApproval&lt;/li&gt;&lt;li&gt;3 - InSigning&lt;/li&gt;&lt;li&gt;4 - InDisbursement&lt;/li&gt;&lt;li&gt;5 - InAdministration&lt;/li&gt;&lt;li&gt;6 - Finished&lt;/li&gt;&lt;li&gt;7 - Cancelled&lt;/li&gt;&lt;li&gt;8 - InApprovalConfirmed&lt;/li&gt;&lt;li&gt;9 - ToBeCancelled&lt;/li&gt;&lt;li&gt;10 - ToBeCancelledConfirmed&lt;/li&gt;&lt;/ul&gt;
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        public CasesSharedCaseModelState State { get; set; } = default!;

        /// <summary>
        /// Slovne nazev stavu Case.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("stateName")]
        public string? StateName { get; set; } = default!;

        /// <summary>
        /// ČÍslo smlouvy. Odpovídá smlouvě uzavřené pro zřízení stavebního spoření, nebo hypotéky. Úvěry ze SS mají jiné číslo smlouvy (jiný suffix), ale nezobrazuje se na case.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("contractNumber")]
        public string? ContractNumber { get; set; } = default!;

        /// <summary>
        /// Cílová částka zobrazující se na dashboardu.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("targetAmount")]
        public decimal TargetAmount { get; set; } = default!;

        /// <summary>
        /// Nazev produktu slovne - ciselnik CaseStates
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("productName")]
        public string? ProductName { get; set; } = default!;

        /// <summary>
        /// Datum vytvoreni Case
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("createdTime")]
        public System.DateTime CreatedTime { get; set; } = default!;

        /// <summary>
        /// Jmeno a prijmeni uzivatele, ktery vytvoril Case
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("createdBy")]
        public string? CreatedBy { get; set; } = default!;

        /// <summary>
        /// Datum a cas posledni zmeny Case.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("stateUpdated")]
        public System.DateTime StateUpdated { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("offerContacts")]
        public SharedTypesContacts? OfferContacts { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("activeTasks")]
        public List<CasesSharedTaskModel>? ActiveTasks { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesSharedCaseOwnerModel
    {

        [System.Text.Json.Serialization.JsonPropertyName("cpm")]
        public string? Cpm { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("icp")]
        public string? Icp { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CasesSharedTaskModel
    {

        [System.Text.Json.Serialization.JsonPropertyName("categoryId")]
        public int? CategoryId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("taskCount")]
        public int TaskCount { get; set; } = default!;

    }

    /// <summary>
    /// Identita klienta
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedTypesCustomerIdentity
    {
        /// <summary>
        /// ID klienta v danem schematu
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public long Id { get; set; } = default!;

        /// <summary>
        /// Schema ve kterem je klient ulozeny - Kb | Mp
        /// <br/>
        /// <br/>&lt;small&gt;Enum Values&lt;/small&gt;&lt;ul&gt;&lt;li&gt;1 - Mp&lt;/li&gt;&lt;li&gt;2 - Kb&lt;/li&gt;&lt;/ul&gt;
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("scheme")]
        public SharedTypesCustomerIdentityScheme Scheme { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedTypesContacts
    {

        [System.Text.Json.Serialization.JsonPropertyName("emailAddress")]
        public SharedTypesEmail? EmailAddress { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("mobilePhone")]
        public SharedTypesPhone? MobilePhone { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedTypesEmail
    {
        /// <summary>
        /// Emailová adresa
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("emailAddress")]
        public string EmailAddress { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedTypesPhone
    {
        /// <summary>
        /// Telefonní číslo
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("phoneNumber")]
        public string PhoneNumber { get; set; } = default!;

        /// <summary>
        /// Předvolba telefonního čísla
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("phoneIDC")]
        public string PhoneIDC { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedTypesPaginationRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("recordOffset")]
        public int RecordOffset { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("sorting")]
        public List<SharedTypesPaginationSortingField>? Sorting { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedTypesPaginationResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("recordOffset")]
        public int RecordOffset { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("recordsTotalSize")]
        public int RecordsTotalSize { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("sorting")]
        public List<SharedTypesPaginationSortingField>? Sorting { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedTypesPaginationSortingField
    {

        [System.Text.Json.Serialization.JsonPropertyName("field")]
        public string Field { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("descending")]
        public bool Descending { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum CasesCancelCaseResponseState
    {

        InProgress = 1,

        InApproval = 2,

        InSigning = 3,

        InDisbursement = 4,

        InAdministration = 5,

        Finished = 6,

        Cancelled = 7,

        InApprovalConfirmed = 8,

        ToBeCancelled = 9,

        ToBeCancelledConfirmed = 10,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum CasesGetCaseMenuFlagsItemFlag
    {

        NoFlag = 0,

        InProcessing = 1,

        ExclamationMark = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum CasesSharedCaseModelState
    {

        InProgress = 1,

        InApproval = 2,

        InSigning = 3,

        InDisbursement = 4,

        InAdministration = 5,

        Finished = 6,

        Cancelled = 7,

        InApprovalConfirmed = 8,

        ToBeCancelled = 9,

        ToBeCancelledConfirmed = 10,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum SharedTypesCustomerIdentityScheme
    {

        MP = 1,

        KB = 2,

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625