SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SalesArrangementType](
    [Id] [int] NOT NULL,
    [Name] [nvarchar](150) NOT NULL,
    [ProductTypeId] [int] NULL,
    [IsDefault] [bit] NOT NULL,
    CONSTRAINT [PK_SalesArrangementType] PRIMARY KEY CLUSTERED
    (
    [Id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ProductTypeExtension](
    [ProductTypeId] [int] NOT NULL,
    [ProductCategory] [tinyint] NOT NULL,
    [MpHomeApiLoanType] [varchar](50) NULL,
    CONSTRAINT [PK_ProductTypeExtension] PRIMARY KEY CLUSTERED
    (
    [ProductTypeId] ASC
     )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO