DROP INDEX IF EXISTS [Idx_CaseId] ON [dbo].[RealEstateValuation];
GO
CREATE NONCLUSTERED INDEX [Idx_CaseId] ON [dbo].[RealEstateValuation]
(
	[CaseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

DROP INDEX IF EXISTS [Idx_RealEstateValuationId] ON [dbo].[RealEstateValuationAttachment];
GO
CREATE NONCLUSTERED INDEX [Idx_RealEstateValuationId] ON [dbo].[RealEstateValuationAttachment]
(
	[RealEstateValuationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
