# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomerData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Identity_pb2 as Identity__pb2
import NullableGrpcDate_pb2 as NullableGrpcDate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43ustomerData.proto\x12\x1a\x44omainServices.CaseService\x1a\x0eIdentity.proto\x1a\x16NullableGrpcDate.proto\"\xaf\x01\n\x0c\x43ustomerData\x12%\n\x08Identity\x18\x01 \x01(\x0b\x32\x13.cis.types.Identity\x12\x1e\n\x16\x46irstNameNaturalPerson\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12=\n\x18\x44\x61teOfBirthNaturalPerson\x18\x04 \x01(\x0b\x32\x1b.cis.types.NullableGrpcDate\x12\x0b\n\x03\x43in\x18\x05 \x01(\tB\'\xaa\x02$DomainServices.CaseService.Contractsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CustomerData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002$DomainServices.CaseService.Contracts'
  _CUSTOMERDATA._serialized_start=91
  _CUSTOMERDATA._serialized_end=266
# @@protoc_insertion_point(module_scope)
