USE [master]
GO

/****** Object:  Database [DataAggregatorService]    Script Date: 01.04.2023 0:05:27 ******/
CREATE DATABASE [DataAggregatorService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataAggregatorService', FILENAME = N'F:\MSSQL15.FAT\MSSQL\DATA\DataAggregatorService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DataAggregatorService_log', FILENAME = N'G:\MSSQL15.FAT\MSSQL\Data\DataAggregatorService_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataAggregatorService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataAggregatorService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataAggregatorService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataAggregatorService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataAggregatorService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataAggregatorService] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataAggregatorService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataAggregatorService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataAggregatorService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataAggregatorService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataAggregatorService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataAggregatorService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataAggregatorService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataAggregatorService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataAggregatorService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataAggregatorService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataAggregatorService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataAggregatorService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataAggregatorService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataAggregatorService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataAggregatorService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataAggregatorService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataAggregatorService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataAggregatorService] SET RECOVERY FULL 
GO

ALTER DATABASE [DataAggregatorService] SET  MULTI_USER 
GO

ALTER DATABASE [DataAggregatorService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataAggregatorService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataAggregatorService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataAggregatorService] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DataAggregatorService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataAggregatorService] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DataAggregatorService] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DataAggregatorService] SET  READ_WRITE 
GO


