USE [master]
GO
CREATE LOGIN [VSSKB\XX_REPORTING_SVC_USR_TEST] FROM WINDOWS WITH DEFAULT_DATABASE=[OperationalReports]

USE [OperationalReports]
CREATE USER [VSSKB\XX_REPORTING_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_REPORTING_SVC_USR_TEST]
GRANT SELECT ON OBJECT::[dbo].[vw_NobyCases] TO [VSSKB\XX_REPORTING_SVC_USR_TEST]