USE [master]
GO
CREATE LOGIN [VSSKB\XX_NOBY_SVC_USR_PROD] FROM WINDOWS WITH DEFAULT_DATABASE=[master]


USE [CIS]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_PROD] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]

USE [CodebookService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_PROD] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]

USE [NotificationService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_PROD] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]
