USE [xxd0vss]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_PROD] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]

USE [xxdvss_hf]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_PROD] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]
