USE [xxvvss]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_PROD] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_PROD]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_PROD]
GRANT EXECUTE ON dbo.getPermissions TO VSSKB\XX_NOBY_SVC_USR_PROD;
GRANT EXECUTE ON dbo.fceGetPersonHF_RIP TO VSSKB\XX_NOBY_SVC_USR_PROD;
GRANT EXECUTE ON dbo.getUserAttributes TO VSSKB\XX_NOBY_SVC_USR_PROD;
GRANT EXECUTE ON dbo.getUserDisplayName TO VSSKB\XX_NOBY_SVC_USR_PROD;
GRANT EXECUTE ON dbo.getUserIdentities TO VSSKB\XX_NOBY_SVC_USR_PROD;
GRANT EXECUTE ON dbo.p_GetPersonHF_RIP TO VSSKB\XX_NOBY_SVC_USR_PROD;
