USE [master]
GO
CREATE LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST] FROM WINDOWS WITH DEFAULT_DATABASE=[master]


USE [CaseService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [CIS]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [CodebookService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [DocumentArchiveService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [HouseholdService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [NOBY]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [OfferService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]

USE [SalesArrangementService]
CREATE USER [VSSKB\XX_NOBY_SVC_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_SVC_USR_TEST]