// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.mpss.api.starbuild.mortgageworkflow.mortgageprocessevents.v1.loanextrapaymentprocesschanged
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ProcessPhase : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ProcessPhase"",""namespace"":""cz.mpss.api.starbuild.mortgageworkflow.mortgageprocessevents.v1.loanextrapaymentprocesschanged"",""fields"":[{""name"":""code"",""type"":""int""},{""name"":""name"",""doc"":"" Attribute has simple type ST_String255 with description: General string of max length 255."",""type"":{""type"":""string"",""avro.java.string"":""String"",""pattern"":""^.{0,255}$""}}]}");
		private int _code;
		/// <summary>
		///  Attribute has simple type ST_String255 with description: General string of max length 255.
		/// </summary>
		private string _name;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ProcessPhase._SCHEMA;
			}
		}
		public int code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		/// <summary>
		///  Attribute has simple type ST_String255 with description: General string of max length 255.
		/// </summary>
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.code;
			case 1: return this.name;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.code = (System.Int32)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
