USE [master]
GO
CREATE LOGIN [VSSKB\XX_NOBY_APP_USR_TEST] FROM WINDOWS WITH DEFAULT_DATABASE=[master]


USE [NOBY]
CREATE USER [VSSKB\XX_NOBY_APP_USR_TEST] FOR LOGIN [VSSKB\XX_NOBY_APP_USR_TEST]
ALTER ROLE [db_datareader] ADD MEMBER [VSSKB\XX_NOBY_APP_USR_TEST]
ALTER ROLE [db_datawriter] ADD MEMBER [VSSKB\XX_NOBY_APP_USR_TEST] 