CREATE TABLE DocumentDataFieldVariant 
(
	DocumentDataFieldId int not null,
	DocumentVariant nvarchar(5) not null,

	CONSTRAINT PK_DocumentDataFieldVariant PRIMARY KEY (DocumentDataFieldId, DocumentVariant),
	CONSTRAINT FK_DocumentDataFieldVariant_DocumentDataField FOREIGN KEY (DocumentDataFieldId) REFERENCES DocumentDataField(DocumentDataFieldId)
)

CREATE TABLE DocumentSpecialDataFieldVariant
(
	DocumentId int not null,
	AcroFieldName nvarchar(100) not null,
	DocumentVariant nvarchar(5) not null,

	CONSTRAINT PK_DocumentSpecialDataFieldVariant PRIMARY KEY (DocumentId, AcroFieldName, DocumentVariant),
	CONSTRAINT FK_DocumentSpecialDataFieldVariant_DocumentSpecialDataField FOREIGN KEY (DocumentId, AcroFieldName) REFERENCES DocumentSpecialDataField(DocumentId, AcroFieldName)
)

--F3601
INSERT INTO DocumentDataFieldVariant VALUES (90, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (90, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (90, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (90, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (91, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (91, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (91, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (91, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (92, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (92, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (92, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (92, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (93, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (93, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (93, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (93, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (94, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (94, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (94, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (94, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (96, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (96, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (96, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (96, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (97, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (97, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (97, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (97, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (98, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (98, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (98, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (98, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (99, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (99, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (99, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (99, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (100, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (100, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (100, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (100, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (101, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (101, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (101, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (101, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (102, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (102, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (102, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (102, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (103, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (103, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (103, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (103, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (104, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (104, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (104, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (104, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (105, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (105, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (105, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (105, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (106, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (106, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (106, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (106, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (107, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (107, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (107, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (107, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (108, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (108, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (108, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (108, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (156, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (156, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (156, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (156, 'D')

INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Zahlavi1Radek', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Zahlavi1Radek', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Zahlavi2Radky', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Zahlavi2Radky', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TypUveru', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TypUveru', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TypUveru', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TypUveru', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseUveruNeucelova', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseUveruNeucelova', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseUveruNeucelova', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseUveruNeucelova', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UcelUveru', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UcelUveru', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UcelUveru', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UcelUveru', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZpusobCerpani', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZpusobCerpani', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZpusobCerpani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZpusobCerpani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DobaCerpani', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DobaCerpani', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DobaCerpani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DobaCerpani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'JmenoPrijmeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'JmenoPrijmeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'JmenoPrijmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'JmenoPrijmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TrvalyPobyt', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TrvalyPobyt', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TrvalyPobyt', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TrvalyPobyt', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'KontaktniAdresa', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'KontaktniAdresa', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'KontaktniAdresa', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'KontaktniAdresa', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DatumNarozeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DatumNarozeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DatumNarozeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DatumNarozeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'RodneCislo', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'RodneCislo', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'RodneCislo', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'RodneCislo', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DokladTotoznosti', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DokladTotoznosti', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DokladTotoznosti', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'DokladTotoznosti', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TelEmail', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TelEmail', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TelEmail', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'TelEmail', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Stav', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Stav', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Stav', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Stav', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UpravaSpolecnehoJmeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UpravaSpolecnehoJmeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UpravaSpolecnehoJmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UpravaSpolecnehoJmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZeZamestnani', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZeZamestnani', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZeZamestnani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZeZamestnani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPodnikani', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPodnikani', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPodnikani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPodnikani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPronajmu', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPronajmu', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPronajmu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZPronajmu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Ostatni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Ostatni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Ostatni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'Ostatni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkyStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkySpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkySpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkySpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'MesSplatkySpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaSpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaSpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NesplJistinaSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremSpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremSpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimUveremSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredSpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredSpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimPredSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VyseLimituDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'NovyLimitDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SplatimDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'ZrusimDebet', 'D')


INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelJmenoPrijmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelJmenoPrijmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelTrvalyPobyt', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelTrvalyPobyt', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelKontaktniAdresa', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelKontaktniAdresa', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelDatumNarozeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelDatumNarozeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelRodneCislo', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelRodneCislo', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelDokladTotoznosti', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelDokladTotoznosti', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelTelEmail', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelTelEmail', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelStav', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelStav', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelUpravaSpolecnehoJmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelUpravaSpolecnehoJmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZeZamestnani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZeZamestnani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZPodnikani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZPodnikani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZPronajmu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZPronajmu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelOstatni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelOstatni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelMesSplatkyHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelMesSplatkyHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNesplJistinaHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNesplJistinaHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimUveremHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimUveremHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimPredHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimPredHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelMesSplatkyStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelMesSplatkyStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNesplJistinaStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNesplJistinaStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimUveremStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimUveremStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimPredStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimPredStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelMesSplatkySpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelMesSplatkySpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNesplJistinaSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNesplJistinaSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimUveremSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimUveremSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimPredSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimPredSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelVyseLimituKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelVyseLimituKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNovyLimitKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNovyLimitKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZrusimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZrusimKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelVyseLimituDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelVyseLimituDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNovyLimitDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelNovyLimitDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelSplatimDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZrusimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'SpoluzadatelZrusimDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UdajeDomacnosti', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UdajeDomacnosti', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UdajeDomacnosti', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'UdajeDomacnosti', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VydajeDomacnosti', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VydajeDomacnosti', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VydajeDomacnosti', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (4, 'VydajeDomacnosti', 'D')

--F3602
INSERT INTO DocumentDataFieldVariant VALUES (113, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (113, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (113, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (113, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (118, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (118, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (118, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (118, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (121, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (121, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (121, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (121, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (116, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (116, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (116, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (116, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (117, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (117, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (117, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (117, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (119, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (119, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (119, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (119, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (110, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (110, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (110, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (110, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (114, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (114, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (114, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (114, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (120, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (120, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (120, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (120, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (111, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (111, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (111, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (111, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (115, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (115, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (115, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (115, 'D')

INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Zahlavi1Radek', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Zahlavi1Radek', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Zahlavi2Radky', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Zahlavi2Radky', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DatumNarozeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DatumNarozeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DatumNarozeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DatumNarozeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DokladTotoznosti', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DokladTotoznosti', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DokladTotoznosti', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'DokladTotoznosti', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'JmenoPrijmeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'JmenoPrijmeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'JmenoPrijmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'JmenoPrijmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'KontaktniAdresa', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'KontaktniAdresa', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'KontaktniAdresa', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'KontaktniAdresa', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkySpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkySpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkySpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkySpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'MesSplatkyStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaSpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaSpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NesplJistinaStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'NovyLimitKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Ostatni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Ostatni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Ostatni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Ostatni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'RodneCislo', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'RodneCislo', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'RodneCislo', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'RodneCislo', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredSpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredSpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimPredStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremHypUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremHypUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremSpotrUvery', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremSpotrUvery', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremStavSpor', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremStavSpor', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SplatimUveremStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Stav', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Stav', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Stav', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'Stav', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TelEmail', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TelEmail', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TelEmail', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TelEmail', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TrvalyPobyt', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TrvalyPobyt', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TrvalyPobyt', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TrvalyPobyt', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TypUveru', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TypUveru', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TypUveru', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'TypUveru', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UcelUveru', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UcelUveru', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UcelUveru', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UcelUveru', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UpravaSpolecnehoJmeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UpravaSpolecnehoJmeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UpravaSpolecnehoJmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'UpravaSpolecnehoJmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'VyseLimituKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZeZamestnani', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZeZamestnani', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZeZamestnani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZeZamestnani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPodnikani', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPodnikani', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPodnikani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPodnikani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPronajmu', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPronajmu', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPronajmu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZPronajmu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimDebet', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimDebet', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimKreditniKarty', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimKreditniKarty', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'ZrusimKreditniKarty', 'D')


INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelDatumNarozeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelDatumNarozeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelDokladTotoznosti', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelDokladTotoznosti', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelJmenoPrijmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelJmenoPrijmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelKontaktniAdresa', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelKontaktniAdresa', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelMesSplatkyHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelMesSplatkyHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelMesSplatkySpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelMesSplatkySpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelMesSplatkyStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelMesSplatkyStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNesplJistinaHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNesplJistinaHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNesplJistinaSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNesplJistinaSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNesplJistinaStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNesplJistinaStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNovyLimitDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNovyLimitDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNovyLimitKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelNovyLimitKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelOstatni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelOstatni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelRodneCislo', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelRodneCislo', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimPredHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimPredHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimPredSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimPredSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimPredStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimPredStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimUveremHypUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimUveremHypUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimUveremSpotrUvery', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimUveremSpotrUvery', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimUveremStavSpor', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelSplatimUveremStavSpor', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelStav', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelStav', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelTelEmail', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelTelEmail', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelTrvalyPobyt', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelTrvalyPobyt', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelUpravaSpolecnehoJmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelUpravaSpolecnehoJmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelVyseLimituDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelVyseLimituDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelVyseLimituKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelVyseLimituKreditniKarty', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZeZamestnani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZeZamestnani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZPodnikani', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZPodnikani', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZPronajmu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZPronajmu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZrusimDebet', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZrusimDebet', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZrusimKreditniKarty', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (5, 'SpoluzadatelZrusimKreditniKarty', 'D')