INSERT INTO Document VALUES (9, 'ZAOZMDLU')

SET IDENTITY_INSERT [dbo].[DataField] ON 

INSERT [dbo].[DataField] ([DataFieldId], [DataServiceId], [FieldPath], [DefaultStringFormat]) VALUES (156, 1, 'SalesArrangement.CustomerChange.Agent.NewAgent', NULL)
INSERT [dbo].[DataField] ([DataFieldId], [DataServiceId], [FieldPath], [DefaultStringFormat]) VALUES (157, 1, 'SalesArrangement.CustomerChange.CommentToChangeRequest.GeneralComment', NULL)

SET IDENTITY_INSERT [dbo].[DataField] OFF

SET IDENTITY_INSERT [dbo].[DocumentDataField] ON 

INSERT [dbo].[DocumentDataField] ([DocumentDataFieldId], [DocumentId], [DocumentVersion], [DataFieldId], [AcroFieldName], [StringFormat], [DefaultTextIfNull]) VALUES (163, 9, '001', 156, 'ZmocnenecProDorucovani', NULL, NULL)
INSERT [dbo].[DocumentDataField] ([DocumentDataFieldId], [DocumentId], [DocumentVersion], [DataFieldId], [AcroFieldName], [StringFormat], [DefaultTextIfNull]) VALUES (164, 9, '001', 157, 'DetailniPopisText', NULL, NULL)

SET IDENTITY_INSERT [dbo].[DocumentDataField] OFF

INSERT INTO DocumentSpecialDataField VALUES (9, 'UvolneniZDluhu', 1, 'ReleaseCustomers', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'PristoupeniKDluhu', 1, 'AddCustomers', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'NoveCisloUctu', 1, 'BankAccount', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'MajitelUctu', 1, 'BankAccountOwner', NULL)

INSERT INTO DocumentSpecialDataField VALUES (9, 'JmenoPrijmeni', 1, 'Customer1.FullName', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'TrvalyPobyt', 1, 'Customer1.Address', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCisloText', 1, 'Customer1.BirthNumberText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCislo', 1, 'Customer1.BirthNumber', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeniText', 1, 'Customer1.DateOfBirthText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeni', 1, 'Customer1.DateOfBirth', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'PodpisJmenoKlienta', 1, 'Customer1.FullName', NULL)

INSERT INTO DocumentSpecialDataField VALUES (9, 'JmenoPrijmeni2', 1, 'Customer2.FullName', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'TrvalyPobyt2', 1, 'Customer2.Address', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCisloText2', 1, 'Customer2.BirthNumberText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCislo2', 1, 'Customer2.BirthNumber', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeniText2', 1, 'Customer2.DateOfBirthText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeni2', 1, 'Customer2.DateOfBirth', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'PodpisJmenoKlienta2', 1, 'Customer2.FullName', NULL)

INSERT INTO DocumentSpecialDataField VALUES (9, 'JmenoPrijmeni3', 1, 'Customer3.FullName', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'TrvalyPobyt3', 1, 'Customer3.Address', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCisloText3', 1, 'Customer3.BirthNumberText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCislo3', 1, 'Customer3.BirthNumber', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeniText3', 1, 'Customer3.DateOfBirthText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeni3', 1, 'Customer3.DateOfBirth', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'PodpisJmenoKlienta3', 1, 'Customer3.FullName', NULL)

INSERT INTO DocumentSpecialDataField VALUES (9, 'JmenoPrijmeni4', 1, 'Customer4.FullName', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'TrvalyPobyt4', 1, 'Customer4.Address', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCisloText4', 1, 'Customer4.BirthNumberText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'RodneCislo4', 1, 'Customer4.BirthNumber', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeniText4', 1, 'Customer4.DateOfBirthText', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'DatumNarozeni4', 1, 'Customer4.DateOfBirth', NULL)
INSERT INTO DocumentSpecialDataField VALUES (9, 'PodpisJmenoKlienta4', 1, 'Customer4.FullName', NULL)

INSERT INTO DocumentDataFieldVariant VALUES (163, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (163, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (163, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (163, 'D')
INSERT INTO DocumentDataFieldVariant VALUES (164, 'A')
INSERT INTO DocumentDataFieldVariant VALUES (164, 'B')
INSERT INTO DocumentDataFieldVariant VALUES (164, 'C')
INSERT INTO DocumentDataFieldVariant VALUES (164, 'D')


INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'UvolneniZDluhu', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PristoupeniKDluhu', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'NoveCisloUctu', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'MajitelUctu', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni', 'A')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta', 'A')


INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'UvolneniZDluhu', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PristoupeniKDluhu', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'NoveCisloUctu', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'MajitelUctu', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni2', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt2', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText2', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo2', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText2', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni2', 'B')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta2', 'B')

INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'UvolneniZDluhu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PristoupeniKDluhu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'NoveCisloUctu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'MajitelUctu', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni2', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt2', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText2', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo2', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText2', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni2', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta2', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni3', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt3', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText3', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo3', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText3', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni3', 'C')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta3', 'C')

INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'UvolneniZDluhu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PristoupeniKDluhu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'NoveCisloUctu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'MajitelUctu', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni2', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt2', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText2', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo2', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText2', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni2', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta2', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni3', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt3', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText3', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo3', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText3', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni3', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta3', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'JmenoPrijmeni4', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'TrvalyPobyt4', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCisloText4', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'RodneCislo4', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeniText4', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'DatumNarozeni4', 'D')
INSERT INTO DocumentSpecialDataFieldVariant VALUES (9, 'PodpisJmenoKlienta4', 'D')