

class Codebooks_all:
    ACADEMICDEGREESAFTER = 'AcademicDegreesAfter'
    ACADEMICDEGREESBEFORE = 'AcademicDegreesBefore'
    ACTIONCODESSAVINGS = 'ActionCodesSavings'
    ACTIONCODESSAVINGSLOAN = 'ActionCodesSavingsLoan'
    CASESTATES = 'CaseStates'
    CLASSIFICATIONOFECONOMICACTIVITIES = 'ClassificationOfEconomicActivities'
    CONTACTTYPES = 'ContactTypes'
    COUNTRIES = 'Countries'
    COUNTRYCODEPHONEIDC = 'CountryCodePhoneIdc'
    CURRENCIES = 'Currencies'
    CUSTOMERPROFILES = 'CustomerProfiles'
    CUSTOMERROLES = 'CustomerRoles'
    ADDRESSTYPES = 'AddressTypes'
    BANKCODES = 'BankCodes'
    DEVELOPERS = 'Developers'
    DEVELOPERPROJECTS = 'DeveloperProjects'
    DOCUMENTONSATYPES = 'DocumentOnSATypes'
    DOCUMENTTEMPLATEVERSIONS = 'DocumentTemplateVersions'
    DOCUMENTTEMPLATEVARIANTS = 'DocumentTemplateVariants'
    DOCUMENTTYPES = 'DocumentTypes'
    DRAWINGDURATIONS = 'DrawingDurations'
    DRAWINGTYPES = 'DrawingTypes'
    EACODESMAIN = 'EaCodesMain'
    EDUCATIONLEVELS = 'EducationLevels'
    EMPLOYMENTTYPES = 'EmploymentTypes'
    FEES = 'Fees'
    FIXEDRATEPERIODS = 'FixedRatePeriods'
    GENDERS = 'Genders'
    HOUSEHOLDTYPES = 'HouseholdTypes'
    IDENTIFICATIONDOCUMENTTYPES = 'IdentificationDocumentTypes'
    IDENTIFICATIONSUBJECTMETHODS = 'IdentificationSubjectMethods'
    INCOMEMAINTYPES = 'IncomeMainTypes'
    INCOMEMAINTYPESAML = 'IncomeMainTypesAML'
    INCOMEFOREIGNTYPES = 'IncomeForeignTypes'
    INCOMEOTHERTYPES = 'IncomeOtherTypes'
    JOBTYPES = 'JobTypes'
    LEGALCAPACITYRESTRICTIONTYPES = 'LegalCapacityRestrictionTypes'
    LOANPURPOSES = 'LoanPurposes'
    LOANKINDS = 'LoanKinds'
    LOANINTERESTRATEANNOUNCEDTYPES = 'LoanInterestRateAnnouncedTypes'
    MANDANTS = 'Mandants'
    MARITALSTATUSES = 'MaritalStatuses'
    MARKETINGACTIONS = 'MarketingActions'
    NETMONTHEARNINGS = 'NetMonthEarnings'
    OBLIGATIONCORRECTIONTYPES = 'ObligationCorrectionTypes'
    OBLIGATIONTYPES = 'ObligationTypes'
    FORMTYPES = 'FormTypes'
    PAYMENTDAYS = 'PaymentDays'
    PAYOUTTYPES = 'PayoutTypes'
    POSTCODES = 'PostCodes'
    PRODUCTTYPES = 'ProductTypes'
    PROFESSIONCATEGORIES = 'ProfessionCategories'
    PROFESSIONTYPES = 'ProfessionTypes'
    PROPERTYSETTLEMENTS = 'PropertySettlements'
    REALESTATETYPES = 'RealEstateTypes'
    REALESTATEPURCHASETYPES = 'RealEstatePurchaseTypes'
    SALESARRANGEMENTSTATES = 'SalesArrangementStates'
    SALESARRANGEMENTTYPES = 'SalesArrangementTypes'
    SIGNATURETYPES = 'SignatureTypes'
    SIGNINGMETHODSFORNATURALPERSON = 'SigningMethodsForNaturalPerson'
    STATEMENTFREQUENCIES = 'StatementFrequencies'
    STATEMENTSUBSCRIPTIONTYPES = 'StatementSubscriptionTypes'
    STATEMENTTYPES = 'StatementTypes'
    TINFORMATSBYCOUNTRY = 'TinFormatsByCountry'
    TINFILLREASONSBYCOUNTRY = 'TinNoFillReasonsByCountry'
    WORKFLOWCONSULTATIONMATRIX = 'WorkflowConsultationMatrix'
    WORKFLOWTASKCONSULTATIONTYPES = 'WorkflowTaskConsultationTypes'
    WORKFLOWTASKSTATESNOBY = 'WorkflowTaskStatesNoby'
    WORKFLOWTASKCATEGORIES = 'WorkflowTaskCategories'
    WORKFLOWTASKSIGNINGRESPONSETYPES = 'WorkflowTaskSigningResponseTypes'
    WORKFLOWTASKSTATES = 'WorkflowTaskStates'
    WORKFLOWTASKTYPES = 'WorkflowTaskTypes'
    WORKSECTORS = 'WorkSectors'



class Codebooks:
    FIXATIONPERIODLENGTH = 'fixation-period-length'
    PRODUCTLOANKINDS = 'product-loan-kinds'
    FIXEDRATEPERIODS = 'fixed-rate-periods'


class ProductTypes:
    MORTGAGE = 20001