# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OfferService.v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Messages import GetOffer_pb2 as Messages_dot_GetOffer__pb2
from Messages import GetMortgageOffer_pb2 as Messages_dot_GetMortgageOffer__pb2
from Messages import GetMortgageOfferDetail_pb2 as Messages_dot_GetMortgageOfferDetail__pb2
from Messages import SimulateMortgage_pb2 as Messages_dot_SimulateMortgage__pb2
from Messages import GetMortgageOfferFPSchedule_pb2 as Messages_dot_GetMortgageOfferFPSchedule__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15OfferService.v1.proto\x12\x1e\x44omainServices.OfferService.v1\x1a\x17Messages/GetOffer.proto\x1a\x1fMessages/GetMortgageOffer.proto\x1a%Messages/GetMortgageOfferDetail.proto\x1a\x1fMessages/SimulateMortgage.proto\x1a)Messages/GetMortgageOfferFPSchedule.proto2\xad\x05\n\x0cOfferService\x12g\n\x08GetOffer\x12,.DomainServices.OfferService.GetOfferRequest\x1a-.DomainServices.OfferService.GetOfferResponse\x12\x7f\n\x10GetMortgageOffer\x12\x34.DomainServices.OfferService.GetMortgageOfferRequest\x1a\x35.DomainServices.OfferService.GetMortgageOfferResponse\x12\x91\x01\n\x16GetMortgageOfferDetail\x12:.DomainServices.OfferService.GetMortgageOfferDetailRequest\x1a;.DomainServices.OfferService.GetMortgageOfferDetailResponse\x12\x7f\n\x10SimulateMortgage\x12\x34.DomainServices.OfferService.SimulateMortgageRequest\x1a\x35.DomainServices.OfferService.SimulateMortgageResponse\x12\x9d\x01\n\x1aGetMortgageOfferFPSchedule\x12>.DomainServices.OfferService.GetMortgageOfferFPScheduleRequest\x1a?.DomainServices.OfferService.GetMortgageOfferFPScheduleResponseB+\xaa\x02(DomainServices.OfferService.Contracts.v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OfferService.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002(DomainServices.OfferService.Contracts.v1'
  _OFFERSERVICE._serialized_start=231
  _OFFERSERVICE._serialized_end=916
# @@protoc_insertion_point(module_scope)
