// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.kb.api.mortgageservicingevents.v3.mortgageapplication
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// The role that a party has in a particular product instance.It can be specific to each product, common across a group of products, or even across all products.E.g. applicant, co-applicant, guarantor for consumer loans#CZ#Role, kterou ma strana v konkretni instanci produktu.Muze byt specificka pro kazdy produkt, spolecna v ramci skupiny produktu nebo dokonce pro vsechny produkty.Napr. zadatel, spoluzadatel, rucitel pro spotrebni uvery. CDM entity name(s): PartyInMktItemInstanceRole.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class PartyInMktItemInstanceRole : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PartyInMktItemInstanceRole\",\"doc\":\"The role that a party" +
				" has in a particular product instance.It can be specific to each product, common" +
				" across a group of products, or even across all products.E.g. applicant, co-appl" +
				"icant, guarantor for consumer loans#CZ#Role, kterou ma strana v konkretni instan" +
				"ci produktu.Muze byt specificka pro kazdy produkt, spolecna v ramci skupiny prod" +
				"uktu nebo dokonce pro vsechny produkty.Napr. zadatel, spoluzadatel, rucitel pro " +
				"spotrebni uvery. CDM entity name(s): PartyInMktItemInstanceRole.\",\"namespace\":\"c" +
				"z.kb.api.mortgageservicingevents.v3.mortgageapplication\",\"fields\":[{\"name\":\"part" +
				"yInMktItemInstanceRoleCode\",\"type\":{\"type\":\"record\",\"name\":\"PartyInMktItemInstan" +
				"ceRoleCode\",\"doc\":\"Multicodebook property representing code of role (unique iden" +
				"tifier) that parties in general can have on products.It is multicodebook because" +
				" roles always exists, but differs per product groups and are not managed central" +
				"ly. CDM entity name(s): PartyInMktItemInstanceRoleCode.\",\"namespace\":\"cz.kb.api." +
				"mortgageservicingevents.v3.mortgageapplication\",\"fields\":[{\"name\":\"code\",\"doc\":\"" +
				"Human readable unique identifier of role on product instance. MultiCodebook valu" +
				"e itself.Unique across all products. Attribute has specific codebook type: CB_Cu" +
				"stomerInMortgageInstanceRole. CDM attribute class name: PartyInMktItemInstanceRo" +
				"leCodeCode. Attribute has simple type CB_MultiCodebookValue with description: Re" +
				"presents information that value can be from more than one codebook. Codebook typ" +
				"e: CB_CustomerInMortgageInstanceRole.\",\"type\":{\"type\":\"string\",\"avro.java.string" +
				"\":\"String\",\"pattern\":\"^.{0,100}$\"}}]}}]}");
		private cz.kb.api.mortgageservicingevents.v3.mortgageapplication.PartyInMktItemInstanceRoleCode _partyInMktItemInstanceRoleCode;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PartyInMktItemInstanceRole._SCHEMA;
			}
		}
		public cz.kb.api.mortgageservicingevents.v3.mortgageapplication.PartyInMktItemInstanceRoleCode partyInMktItemInstanceRoleCode
		{
			get
			{
				return this._partyInMktItemInstanceRoleCode;
			}
			set
			{
				this._partyInMktItemInstanceRoleCode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.partyInMktItemInstanceRoleCode;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.partyInMktItemInstanceRoleCode = (cz.kb.api.mortgageservicingevents.v3.mortgageapplication.PartyInMktItemInstanceRoleCode)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
