from enum import Enum

class EProcessKey(Enum):
    OFFER_ID = 'OFFER_ID'
    CASE_ID = 'CASE_ID'
    SALES_ARRAMGEMENT_ID = 'SALES_ARRAMGEMENT_ID'
    HOUSEHOLD_ID = 'HOUSEHOLD_ID'
    CUSTOMER_ON_SA_ID = 'CUSTOMER_ON_SA_ID'
    INCOME_ID = 'INCOME_ID'
    OBLIGATION_ID = 'OBLIGATION_ID'