# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PaginationRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PaginationSortingField_pb2 as PaginationSortingField__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PaginationRequest.proto\x12\tcis.types\x1a\x1cPaginationSortingField.proto\"o\n\x11PaginationRequest\x12\x14\n\x0crecordOffset\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x32\n\x07sorting\x18\x03 \x03(\x0b\x32!.cis.types.PaginationSortingFieldB#\xaa\x02 CIS.Infrastructure.gRPC.CisTypesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PaginationRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002 CIS.Infrastructure.gRPC.CisTypes'
  _PAGINATIONREQUEST._serialized_start=68
  _PAGINATIONREQUEST._serialized_end=179
# @@protoc_insertion_point(module_scope)
