namespace DomainServices.CodebookService.Contracts.v1;

public partial class GenericCodebookResponse : IItemsResponse<GenericCodebookResponse.Types.GenericCodebookItem> { }
public partial class GenericCodebookWithCodeResponse : IItemsResponse<GenericCodebookWithCodeResponse.Types.GenericCodebookWithCodeItem> { }
public partial class BankCodesResponse : IItemsResponse<BankCodesResponse.Types.BankCodeItem> { }
public partial class CaseStatesResponse : IItemsResponse<CaseStatesResponse.Types.CaseStateItem> { }
public partial class CollateralTypesResponse : IItemsResponse<CollateralTypesResponse.Types.CollateralTypeItem> { }
public partial class ContactTypesResponse : IItemsResponse<ContactTypesResponse.Types.ContactTypeItem> { }
public partial class CountriesResponse : IItemsResponse<CountriesResponse.Types.CountryItem> { }
public partial class CountryCodePhoneIdcResponse : IItemsResponse<CountryCodePhoneIdcResponse.Types.CountryCodePhoneIdcItem> { }
public partial class CurrenciesResponse : IItemsResponse<CurrenciesResponse.Types.CurrencyItem> { }
public partial class CustomerRolesResponse : IItemsResponse<CustomerRolesResponse.Types.CustomerRoleItem> { }
public partial class DeveloperSearchResponse : IItemsResponse<DeveloperSearchResponse.Types.DeveloperSearchItem> { }
public partial class DocumentFileTypesResponse : IItemsResponse<DocumentFileTypesResponse.Types.DocumentFileTypeItem> { }
public partial class DocumentOnSATypesResponse : IItemsResponse<DocumentOnSATypesResponse.Types.DocumentOnSATypeItem> { }
public partial class DocumentTemplateTypesResponse : IItemsResponse<DocumentTemplateTypesResponse.Types.DocumentTemplateTypeItem> { }
public partial class DocumentTemplateVariantsResponse : IItemsResponse<DocumentTemplateVariantsResponse.Types.DocumentTemplateVariantItem> { }
public partial class DocumentTemplateVersionsResponse : IItemsResponse<DocumentTemplateVersionsResponse.Types.DocumentTemplateVersionItem> { }
public partial class DocumentTypesResponse : IItemsResponse<DocumentTypesResponse.Types.DocumentTypeItem> { }
public partial class DrawingDurationsResponse : IItemsResponse<DrawingDurationsResponse.Types.DrawingDurationItem> { }
public partial class DrawingTypesResponse : IItemsResponse<DrawingTypesResponse.Types.DrawingTypeItem> { }
public partial class EaCodesMainResponse : IItemsResponse<EaCodesMainResponse.Types.EaCodesMainItem> { }
public partial class EducationLevelsResponse : IItemsResponse<EducationLevelsResponse.Types.EducationLevelItem> { }
public partial class FeesResponse : IItemsResponse<FeesResponse.Types.FeeItem> { }
public partial class FixedRatePeriodsResponse : IItemsResponse<FixedRatePeriodsResponse.Types.FixedRatePeriodItem> { }
public partial class FormTypesResponse : IItemsResponse<FormTypesResponse.Types.FormTypeItem> { }
public partial class GendersResponse : IItemsResponse<GendersResponse.Types.GenderItem> { }
public partial class GetDeveloperResponse : IItemsResponse<GetDeveloperResponse.Types.GetDeveloperItem> { }
public partial class GetDeveloperProjectResponse : IItemsResponse<GetDeveloperProjectResponse.Types.GetDeveloperProjectItem> { }
public partial class GetGeneralDocumentListResponse : IItemsResponse<GetGeneralDocumentListResponse.Types.GetGeneralDocumentListItem> { }
public partial class GetOperatorResponse : IItemsResponse<GetOperatorResponse.Types.GetOperatorItem> { }
public partial class HouseholdTypesResponse : IItemsResponse<HouseholdTypesResponse.Types.HouseholdTypeItem> { }
public partial class HousingConditionsResponse : IItemsResponse<HousingConditionsResponse.Types.HousingConditionItem> { }
public partial class ChannelsResponse : IItemsResponse<ChannelsResponse.Types.ChannelItem> { }
public partial class IdentificationDocumentTypesResponse : IItemsResponse<IdentificationDocumentTypesResponse.Types.IdentificationDocumentTypeItem> { }
public partial class IdentitySchemesResponse : IItemsResponse<IdentitySchemesResponse.Types.IdentitySchemeItem> { }
public partial class IncomeMainTypesAMLResponse : IItemsResponse<IncomeMainTypesAMLResponse.Types.IncomeMainTypesAMLItem> { }
public partial class JobTypesResponse : IItemsResponse<JobTypesResponse.Types.JobTypeItem> { }
public partial class LegalCapacityRestrictionTypesResponse : IItemsResponse<LegalCapacityRestrictionTypesResponse.Types.LegalCapacityRestrictionTypeItem> { }
public partial class LoanKindsResponse : IItemsResponse<LoanKindsResponse.Types.LoanKindItem> { }
public partial class LoanPurposesResponse : IItemsResponse<LoanPurposesResponse.Types.LoanPurposeItem> { }
public partial class MaritalStatusesResponse : IItemsResponse<MaritalStatusesResponse.Types.MaritalStatuseItem> { }