// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.kb.osbs.mcs.sender.sendapi.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Date and time range.At least one of min, max must be defined. If only one is defined, then the other one is automatically +,- infinity. CDM entity name: DateTimeRange.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class DeliveryTiming : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""DeliveryTiming"",""doc"":""Date and time range.At least one of min, max must be defined. If only one is defined, then the other one is automatically +,- infinity. CDM entity name: DateTimeRange."",""namespace"":""cz.kb.osbs.mcs.sender.sendapi.v1"",""fields"":[{""name"":""max"",""doc"":""max, inclusive. CDM attribute class name: DateTimeRangeMax."",""default"":null,""type"":[""null"",{""type"":""long"",""logicalType"":""local-timestamp-millis""}]},{""name"":""min"",""doc"":""min, inclusive. CDM attribute class name: DateTimeRangeMin."",""default"":null,""type"":[""null"",{""type"":""long"",""logicalType"":""local-timestamp-millis""}]}]}");
		/// <summary>
		/// max, inclusive. CDM attribute class name: DateTimeRangeMax.
		/// </summary>
		private System.Nullable<System.DateTime> _max;
		/// <summary>
		/// min, inclusive. CDM attribute class name: DateTimeRangeMin.
		/// </summary>
		private System.Nullable<System.DateTime> _min;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return DeliveryTiming._SCHEMA;
			}
		}
		/// <summary>
		/// max, inclusive. CDM attribute class name: DateTimeRangeMax.
		/// </summary>
		public System.Nullable<System.DateTime> max
		{
			get
			{
				return this._max;
			}
			set
			{
				this._max = value;
			}
		}
		/// <summary>
		/// min, inclusive. CDM attribute class name: DateTimeRangeMin.
		/// </summary>
		public System.Nullable<System.DateTime> min
		{
			get
			{
				return this._min;
			}
			set
			{
				this._min = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.max;
			case 1: return this.min;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.max = (System.Nullable<System.DateTime>)fieldValue; break;
			case 1: this.min = (System.Nullable<System.DateTime>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
