USE [master]
GO

/****** Object:  Database [HouseholdService]    Script Date: 19.01.2023 1:42:24 ******/
CREATE DATABASE [HouseholdService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HouseholdService', FILENAME = N'R:\Data_Bronze_12_PP\HouseholdService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HouseholdService_log', FILENAME = N'R:\Data_Silver_07_PP\HouseholdService_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HouseholdService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HouseholdService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HouseholdService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HouseholdService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HouseholdService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HouseholdService] SET ARITHABORT OFF 
GO

ALTER DATABASE [HouseholdService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HouseholdService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HouseholdService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HouseholdService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HouseholdService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HouseholdService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HouseholdService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HouseholdService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HouseholdService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HouseholdService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HouseholdService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HouseholdService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HouseholdService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HouseholdService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HouseholdService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HouseholdService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HouseholdService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HouseholdService] SET RECOVERY FULL 
GO

ALTER DATABASE [HouseholdService] SET  MULTI_USER 
GO

ALTER DATABASE [HouseholdService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HouseholdService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HouseholdService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HouseholdService] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HouseholdService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HouseholdService] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HouseholdService] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HouseholdService] SET  READ_WRITE 
GO


