from enum import Enum

class ECodebook(Enum):
    AcademicDegreesAfter = 'AcademicDegreesAfter'
    AcademicDegreesBefore = 'AcademicDegreesBefore'
    BankCodes = 'BankCodes'
    CaseStates = 'CaseStates'
    ClassificationOfEconomicActivities = 'ClassificationOfEconomicActivities'
    ContactTypes = 'ContactTypes'
    Countries = 'Countries'
    Currencies = 'Currencies'
    CustomerProfiles = 'CustomerProfiles'
    CustomerRoles = 'CustomerRoles'
    Developers = 'Developers'
    # DeveloperProjects = 'DeveloperProjects' # ?! contains more than 4500 rows (on FAT env)
    DrawingDurations = 'DrawingDurations'
    DrawingTypes = 'DrawingTypes'
    EducationLevels = 'EducationLevels'
    EmploymentTypes = 'EmploymentTypes'
    Fees = 'Fees'
    FixedRatePeriods = 'FixedRatePeriods'
    Genders = 'Genders'
    HouseholdTypes = 'HouseholdTypes'
    IdentificationDocumentTypes = 'IdentificationDocumentTypes'
    IncomeMainTypes = 'IncomeMainTypes'
    IncomeForeignTypes = 'IncomeForeignTypes'
    IncomeOtherTypes = 'IncomeOtherTypes'
    JobTypes = 'JobTypes'
    LegalCapacities = 'LegalCapacities'
    LoanInterestRateAnnouncedTypes = 'LoanInterestRateAnnouncedTypes'
    LoanPurposes = 'LoanPurposes'
    LoanKinds = 'LoanKinds'
    Mandants = 'Mandants'
    MaritalStatuses = 'MaritalStatuses'
    ObligationCorrectionTypes = 'ObligationCorrectionTypes'
    ObligationTypes = 'ObligationTypes'
    PaymentDays = 'PaymentDays'
    PostCodes = 'PostCodes'
    ProductTypes = 'ProductTypes'
    PropertySettlements = 'PropertySettlements'
    RealEstateTypes = 'RealEstateTypes'
    RealEstatePurchaseTypes = 'RealEstatePurchaseTypes'
    SalesArrangementStates = 'SalesArrangementStates'
    SalesArrangementTypes = 'SalesArrangementTypes'
    SignatureTypes = 'SignatureTypes'
    StatementTypes = 'StatementTypes'
    WorkflowTaskCategories = 'WorkflowTaskCategories'
    WorkflowTaskStates = 'WorkflowTaskStates'
    WorkflowTaskTypes = 'WorkflowTaskTypes'
    WorkSectors = 'WorkSectors'

# all codebooks:
# print(','.join( list( e.value for e in ECodebook)))